//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.SEL.Views.AcompanhamentoSelecao.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.SEL.Views.AcompanhamentoSelecao.App_LocalResources.M" +
                            "etadataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao informar um período, serão retornados somente processos cuja etapa de inscrição coincide com o período informado..
        /// </summary>
        public static string AcompanhamentoSelecaoFiltroDynamicModel_DataFim_FillInstructions {
            get {
                return ResourceManager.GetString("AcompanhamentoSelecaoFiltroDynamicModel_DataFim_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao informar um período, serão retornados somente processos cuja etapa de seleção ou convocação coincidem com o período informado..
        /// </summary>
        public static string AcompanhamentoSelecaoFiltroViewModel_DataFim_FillInstructions {
            get {
                return ResourceManager.GetString("AcompanhamentoSelecaoFiltroViewModel_DataFim_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Processo.
        /// </summary>
        public static string AcompanhamentoSelecaoFiltroViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("AcompanhamentoSelecaoFiltroViewModel_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidato:.
        /// </summary>
        public static string Candidato {
            get {
                return ResourceManager.GetString("Candidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos por oferta.
        /// </summary>
        public static string CandidatosConfirmados {
            get {
                return ResourceManager.GetString("CandidatosConfirmados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desistências.
        /// </summary>
        public static string CandidatosDesistentes {
            get {
                return ResourceManager.GetString("CandidatosDesistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excedências.
        /// </summary>
        public static string CandidatosExcedentes {
            get {
                return ResourceManager.GetString("CandidatosExcedentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovações.
        /// </summary>
        public static string CandidatosReprovados {
            get {
                return ResourceManager.GetString("CandidatosReprovados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleções.
        /// </summary>
        public static string CandidatosSelecionados {
            get {
                return ResourceManager.GetString("CandidatosSelecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string ConsultaCandidatosProcessoFiltroViewModel_Descricao {
            get {
                return ResourceManager.GetString("ConsultaCandidatosProcessoFiltroViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item da hierarquia de oferta.
        /// </summary>
        public static string ConsultaCandidatosProcessoFiltroViewModel_SeqItemHierarquiaOferta {
            get {
                return ResourceManager.GetString("ConsultaCandidatosProcessoFiltroViewModel_SeqItemHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string ConsultaCandidatosProcessoFiltroViewModel_SeqMotivo {
            get {
                return ResourceManager.GetString("ConsultaCandidatosProcessoFiltroViewModel_SeqMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string ConsultaCandidatosProcessoFiltroViewModel_SeqOferta {
            get {
                return ResourceManager.GetString("ConsultaCandidatosProcessoFiltroViewModel_SeqOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ConsultaCandidatosProcessoFiltroViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("ConsultaCandidatosProcessoFiltroViewModel_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ªNota/ %Bolsa.
        /// </summary>
        public static string ConsultaCandidatosProcessoListaViewModel_Nota {
            get {
                return ResourceManager.GetString("ConsultaCandidatosProcessoListaViewModel_Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ªNota/ %Financiamento.
        /// </summary>
        public static string ConsultaCandidatosProcessoListaViewModel_SegundaNota {
            get {
                return ResourceManager.GetString("ConsultaCandidatosProcessoListaViewModel_SegundaNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocações.
        /// </summary>
        public static string Convocados {
            get {
                return ResourceManager.GetString("Convocados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocações confirmadas.
        /// </summary>
        public static string ConvocadosConfirmados {
            get {
                return ResourceManager.GetString("ConvocadosConfirmados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocações desistentes.
        /// </summary>
        public static string ConvocadosDesistentes {
            get {
                return ResourceManager.GetString("ConvocadosDesistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string DataAlteracaoOferta {
            get {
                return ResourceManager.GetString("DataAlteracaoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa da alteração:.
        /// </summary>
        public static string JustificativaAlteracaoOferta {
            get {
                return ResourceManager.GetString("JustificativaAlteracaoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa da inscrição:.
        /// </summary>
        public static string JustificativaInscricao {
            get {
                return ResourceManager.GetString("JustificativaInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa:.
        /// </summary>
        public static string MotivoSituacaoViewModel_Justificativa {
            get {
                return ResourceManager.GetString("MotivoSituacaoViewModel_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo:.
        /// </summary>
        public static string MotivoSituacaoViewModel_Motivo {
            get {
                return ResourceManager.GetString("MotivoSituacaoViewModel_Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta:.
        /// </summary>
        public static string Oferta {
            get {
                return ResourceManager.GetString("Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta atual:.
        /// </summary>
        public static string OfertaAtual {
            get {
                return ResourceManager.GetString("OfertaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidato.
        /// </summary>
        public static string OfertaCabecalhoViewModel_Candidato {
            get {
                return ResourceManager.GetString("OfertaCabecalhoViewModel_Candidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº inscrição.
        /// </summary>
        public static string OfertaCabecalhoViewModel_NumeroInscricao {
            get {
                return ResourceManager.GetString("OfertaCabecalhoViewModel_NumeroInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta original.
        /// </summary>
        public static string OfertaCabecalhoViewModel_OfertaOriginal {
            get {
                return ResourceManager.GetString("OfertaCabecalhoViewModel_OfertaOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta original:.
        /// </summary>
        public static string OfertaOriginal {
            get {
                return ResourceManager.GetString("OfertaOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa.
        /// </summary>
        public static string OfertaViewModel_JustificativaAlteracaoOferta {
            get {
                return ResourceManager.GetString("OfertaViewModel_JustificativaAlteracaoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa da inscrição.
        /// </summary>
        public static string OfertaViewModel_JustificativaInscricao {
            get {
                return ResourceManager.GetString("OfertaViewModel_JustificativaInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova oferta.
        /// </summary>
        public static string OfertaViewModel_SeqOferta {
            get {
                return ResourceManager.GetString("OfertaViewModel_SeqOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_Descricao {
            get {
                return ResourceManager.GetString("PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item da Hierarquia de Oferta.
        /// </summary>
        public static string PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_SeqItemHierarquiaOferta {
            get {
                return ResourceManager.GetString("PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_SeqItemHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_SeqOferta {
            get {
                return ResourceManager.GetString("PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_SeqOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("PosicaoConsolidadaPorGrupoOfertaFiltroViewModel_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de ofertas.
        /// </summary>
        public static string PosicaoConsolidadaPorGrupoOfertaListaViewModel_Descricao {
            get {
                return ResourceManager.GetString("PosicaoConsolidadaPorGrupoOfertaListaViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string SeqOferta {
            get {
                return ResourceManager.GetString("SeqOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta atual.
        /// </summary>
        public static string SeqOfertaAtual {
            get {
                return ResourceManager.GetString("SeqOfertaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável:.
        /// </summary>
        public static string UsuarioAlteracaoOferta {
            get {
                return ResourceManager.GetString("UsuarioAlteracaoOferta", resourceCulture);
            }
        }
    }
}
