//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.SEL.Views.AcompanhamentoSelecao.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.SEL.Views.AcompanhamentoSelecao.App_LocalResources.U" +
                            "IResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Candidatos do Grupo de Ofertas.
        /// </summary>
        public static string _CabecalhoProcessoGrupoOferta_Botao_Consultar_Inscricoes_Grupo_Oferta {
            get {
                return ResourceManager.GetString("_CabecalhoProcessoGrupoOferta_Botao_Consultar_Inscricoes_Grupo_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Candidatos da Oferta.
        /// </summary>
        public static string _DetalheOfertaGrupoOferta_Botao_Consultar_Inscricoes_Oferta {
            get {
                return ResourceManager.GetString("_DetalheOfertaGrupoOferta_Botao_Consultar_Inscricoes_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar inscrição.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Consultainscricao {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Consultainscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar inscrição.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Consultainscricao_Title {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Consultainscricao_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar notificação.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Consultanotificacao {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Consultanotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar notificação.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Consultanotificacao_Title {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Consultanotificacao_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar situação da convocação.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Convocacao {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Convocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar situação da convocação.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Convocacao_Tooltip {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Convocacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar histórico de situação.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Historicosituacao {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Historicosituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar histórico de situação.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Historicosituacao_Title {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Historicosituacao_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançar resultado.
        /// </summary>
        public static string _ListarCandidatosProcesso_Botao_Lancamentoresultado {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Botao_Lancamentoresultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados da Pesquisa.
        /// </summary>
        public static string _ListarCandidatosProcesso_gridListaCandidatos_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_gridListaCandidatos_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar justificativa.
        /// </summary>
        public static string _ListarCandidatosProcesso_ModalJustificativaOferta_Title {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_ModalJustificativaOferta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar justificativa.
        /// </summary>
        public static string _ListarCandidatosProcesso_ModalParecerResponsavel_Title {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_ModalParecerResponsavel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string _ListarCandidatosProcesso_Situacao {
            get {
                return ResourceManager.GetString("_ListarCandidatosProcesso_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posição dos processos.
        /// </summary>
        public static string _ListarPosicaoConsolidada_gridPosicaoConsolidada_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarPosicaoConsolidada_gridPosicaoConsolidada_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos por oferta.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_CandidatosConfirmados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_CandidatosConfirmados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desistências.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_CandidatosDesistentes {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_CandidatosDesistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excedências.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_CandidatosExcedentes {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_CandidatosExcedentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovações.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_CandidatosReprovados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_CandidatosReprovados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleções.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_CandidatosSelecionados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_CandidatosSelecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocações.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_Convocados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_Convocados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocações confirmadas.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_ConvocadosConfirmados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_ConvocadosConfirmados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocações desistentes.
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_ConvocadosDesistentes {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_ConvocadosDesistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os candidatos são contabilizados em cada uma das ofertas às quais estão associados. Ou seja, se o candidato estiver associado a uma única oferta, ele é contabilizado apenas uma vez, porém, se o candidato estiver associado a três ofertas, ele é contabilizado em cada uma delas, de acordo com a situação dele nestas..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Label_Inicial {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Label_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que passaram para etapa de seleção..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_CandidatosConfirmados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_CandidatosConfirmados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que desistiram na etapa de seleção..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_CandidatosDesistentes {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_CandidatosDesistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que ficaram como excedentes..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_CandidatosExcedentes {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_CandidatosExcedentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que foram reprovados..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_CandidatosReprovados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_CandidatosReprovados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que foram selecionados..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_CandidatosSelecionados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_CandidatosSelecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que foram convocados..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_Convocados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_Convocados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que confirmaram a convocação..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_ConvocadosConfirmados {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_ConvocadosConfirmados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total de candidatos por oferta que desistiram após a convocação..
        /// </summary>
        public static string _ModalLegendaPosicaoConsolidada_Texto_ConvocadosDesistentes {
            get {
                return ResourceManager.GetString("_ModalLegendaPosicaoConsolidada_Texto_ConvocadosDesistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar oferta.
        /// </summary>
        public static string Botao_AlterarOferta {
            get {
                return ResourceManager.GetString("Botao_AlterarOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar oferta.
        /// </summary>
        public static string Botao_AlterarOferta_Tooltip {
            get {
                return ResourceManager.GetString("Botao_AlterarOferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise da Seleção em Lote.
        /// </summary>
        public static string Botao_Analiselote {
            get {
                return ResourceManager.GetString("Botao_Analiselote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise da Seleção em Lote.
        /// </summary>
        public static string Botao_Analiselote_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Analiselote_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Posição Consolidada da Seleção por Grupo de Oferta e por Oferta.
        /// </summary>
        public static string Botao_Consultaposiçãoconsolidadagrupoofertasoferta {
            get {
                return ResourceManager.GetString("Botao_Consultaposiçãoconsolidadagrupoofertasoferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Posição Consolidada da Seleção por Grupo de Oferta e por Oferta.
        /// </summary>
        public static string Botao_Consultaposiçãoconsolidadagrupoofertasoferta_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Consultaposiçãoconsolidadagrupoofertasoferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Candidatos do Processo.
        /// </summary>
        public static string Botao_Consultaselecoesprocesso {
            get {
                return ResourceManager.GetString("Botao_Consultaselecoesprocesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Candidatos do Processo.
        /// </summary>
        public static string Botao_Consultaselecoesprocesso_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Consultaselecoesprocesso_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer lançamento de resultado.
        /// </summary>
        public static string Botao_Desfazerlancamentoresultado {
            get {
                return ResourceManager.GetString("Botao_Desfazerlancamentoresultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer lançamento de resultado.
        /// </summary>
        public static string Botao_Desfazerlancamentoresultado_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Desfazerlancamentoresultado_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Posição Consolidada da Seleção por Grupo de Ofertas e por Oferta.
        /// </summary>
        public static string ConsultarProcessoPorGrupoOferta_Title {
            get {
                return ResourceManager.GetString("ConsultarProcessoPorGrupoOferta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocação.
        /// </summary>
        public static string ConsultaSelecoesProcesso_Label_Convocacao {
            get {
                return ResourceManager.GetString("ConsultaSelecoesProcesso_Label_Convocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa da inscrição.
        /// </summary>
        public static string ConsultaSelecoesProcesso_Label_JustificativaOferta {
            get {
                return ResourceManager.GetString("ConsultaSelecoesProcesso_Label_JustificativaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo/Justificativa da situação.
        /// </summary>
        public static string ConsultaSelecoesProcesso_Label_JustificativaSituacao {
            get {
                return ResourceManager.GetString("ConsultaSelecoesProcesso_Label_JustificativaSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta alteração de situação enviará um e-mail de notificação automático para o(s) candidato(s) selecionado(s), caso isso tenha sido configurado no processo. Confirma a alteração da situação?.
        /// </summary>
        public static string ConsultaSelecoesProcesso_Mensagem_Confirmacao_Alteracao_Situacao {
            get {
                return ResourceManager.GetString("ConsultaSelecoesProcesso_Mensagem_Confirmacao_Alteracao_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Candidatos do Processo.
        /// </summary>
        public static string ConsultaSelecoesProcesso_Title {
            get {
                return ResourceManager.GetString("ConsultaSelecoesProcesso_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção:.
        /// </summary>
        public static string ConsultaSelecoesProcesso_Titulo_Confirmacao_Alteracao_Situacao {
            get {
                return ResourceManager.GetString("ConsultaSelecoesProcesso_Titulo_Confirmacao_Alteracao_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da alteração da oferta.
        /// </summary>
        public static string fieldsetAlteracaoferta_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("fieldsetAlteracaoferta_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Posição Consolidada da Seleção por Processo.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de oferta realizada com sucesso..
        /// </summary>
        public static string Mensagem_Sucesso_Alteracao_Oferta {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Alteracao_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja desfazer o lançamento do resultado do candidato {0}?.
        /// </summary>
        public static string Mensagem_Texto_DesfazerLancamento {
            get {
                return ResourceManager.GetString("Mensagem_Texto_DesfazerLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer lançamento.
        /// </summary>
        public static string Mensagem_Titulo_DesfazerLancamento {
            get {
                return ResourceManager.GetString("Mensagem_Titulo_DesfazerLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da oferta do candidato.
        /// </summary>
        public static string ModalDadosOferta_Title {
            get {
                return ResourceManager.GetString("ModalDadosOferta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Oferta.
        /// </summary>
        public static string Titulo_AlterarOferta {
            get {
                return ResourceManager.GetString("Titulo_AlterarOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da Oferta do Candidato.
        /// </summary>
        public static string Titulo_DadosOferta {
            get {
                return ResourceManager.GetString("Titulo_DadosOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda.
        /// </summary>
        public static string Titulo_Modal_Legenda {
            get {
                return ResourceManager.GetString("Titulo_Modal_Legenda", resourceCulture);
            }
        }
    }
}
