//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Inscricao.Areas.INS.Views.Inscricao.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Inscricao.Areas.INS.Views.Inscricao.App_LocalResources.MetadataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string CidadeNaturalidade {
            get {
                return ResourceManager.GetString("CidadeNaturalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string DescricaoDisplay {
            get {
                return ResourceManager.GetString("DescricaoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        internal static string InscricaoDocumentoAdicionalViewModel_SeqDocumentoRequerido {
            get {
                return ResourceManager.GetString("InscricaoDocumentoAdicionalViewModel_SeqDocumentoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string InscricaoDocumentoListaViewModel_DescricaoArquivoAnexado {
            get {
                return ResourceManager.GetString("InscricaoDocumentoListaViewModel_DescricaoArquivoAnexado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento(s).
        /// </summary>
        internal static string InscricaoDocumentoListaViewModel_DescricaoTipoDocumento {
            get {
                return ResourceManager.GetString("InscricaoDocumentoListaViewModel_DescricaoTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        internal static string InscricaoDocumentoListaViewModel_NomeArquivoAnexado {
            get {
                return ResourceManager.GetString("InscricaoDocumentoListaViewModel_NomeArquivoAnexado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        internal static string InscricaoDocumentoObrigatorioViewModel_DescricaoTipoDocumentoApresentacao {
            get {
                return ResourceManager.GetString("InscricaoDocumentoObrigatorioViewModel_DescricaoTipoDocumentoApresentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        internal static string InscricaoDocumentoOpcionalViewModel_DescricaoTipoDocumentoApresentacao {
            get {
                return ResourceManager.GetString("InscricaoDocumentoOpcionalViewModel_DescricaoTipoDocumentoApresentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        internal static string InscricaoDocumentoViewModel_ArquivoAnexado {
            get {
                return ResourceManager.GetString("InscricaoDocumentoViewModel_ArquivoAnexado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string InscricaoDocumentoViewModel_DescricaoArquivoAnexado {
            get {
                return ResourceManager.GetString("InscricaoDocumentoViewModel_DescricaoArquivoAnexado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo documento.
        /// </summary>
        internal static string InscricaoDocumentoViewModel_SeqDocumentoRequerido {
            get {
                return ResourceManager.GetString("InscricaoDocumentoViewModel_SeqDocumentoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa.
        /// </summary>
        internal static string InscricaoOfertaListaViewModel_JustificativaInscricao {
            get {
                return ResourceManager.GetString("InscricaoOfertaListaViewModel_JustificativaInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa.
        /// </summary>
        internal static string InscricaoOfertaViewModel_JustificativaInscricao {
            get {
                return ResourceManager.GetString("InscricaoOfertaViewModel_JustificativaInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas.
        /// </summary>
        internal static string InscricaoOfertaViewModel_OpcaoLookupOfertas {
            get {
                return ResourceManager.GetString("InscricaoOfertaViewModel_OpcaoLookupOfertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção.
        /// </summary>
        internal static string InscricaoOfertaViewModel_SeqOferta {
            get {
                return ResourceManager.GetString("InscricaoOfertaViewModel_SeqOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione o botão de pesquisar a direita para realizar a seleção.
        /// </summary>
        internal static string InscricaoOfertaViewModel_SeqOferta_FillInstructions {
            get {
                return ResourceManager.GetString("InscricaoOfertaViewModel_SeqOferta_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        internal static string NumeroIdentidade {
            get {
                return ResourceManager.GetString("NumeroIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de itens.
        /// </summary>
        internal static string NumeroItens {
            get {
                return ResourceManager.GetString("NumeroItens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgão emissor.
        /// </summary>
        internal static string OrgaoEmissorIdentidade {
            get {
                return ResourceManager.GetString("OrgaoEmissorIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de opções para as quais deseja ser convocado(a), respeitando a ordem de prioridade.
        /// </summary>
        internal static string PaginaComprovanteInscricaoViewModel_NumeroOpcoesDesejadas {
            get {
                return ResourceManager.GetString("PaginaComprovanteInscricaoViewModel_NumeroOpcoesDesejadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de opções para as quais deseja ser convocado(a), respeitando a ordem de prioridade.
        /// </summary>
        internal static string PaginaConfirmarInscricaoViewModel_NumeroOpcoesDesejadas {
            get {
                return ResourceManager.GetString("PaginaConfirmarInscricaoViewModel_NumeroOpcoesDesejadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de opções para as quais deseja ser convocado(a), respeitando a ordem de prioridade.
        /// </summary>
        internal static string PaginaSelecaoOfertaViewModel_NumeroOpcoesDesejadas {
            get {
                return ResourceManager.GetString("PaginaSelecaoOfertaViewModel_NumeroOpcoesDesejadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        internal static string ProcessoViewModel_Titulo {
            get {
                return ResourceManager.GetString("ProcessoViewModel_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        internal static string UfIdentidade {
            get {
                return ResourceManager.GetString("UfIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturalidade.
        /// </summary>
        internal static string UfNaturalidade {
            get {
                return ResourceManager.GetString("UfNaturalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do item.
        /// </summary>
        internal static string ValorEventoTaxa {
            get {
                return ResourceManager.GetString("ValorEventoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do item.
        /// </summary>
        internal static string ValorItem {
            get {
                return ResourceManager.GetString("ValorItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total do item.
        /// </summary>
        internal static string ValorTotalTaxa {
            get {
                return ResourceManager.GetString("ValorTotalTaxa", resourceCulture);
            }
        }
    }
}
