//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.Inscricoes.Common.Areas.SEL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.Inscricoes.Common.Areas.SEL.Resources.ExceptionsResource", typeof(ExceptionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas candidatos selecionados ou excedentes podem ser convocados..
        /// </summary>
        public static string CandidatoComSituacaoInvalidaParaConvocacaoException {
            get {
                return ResourceManager.GetString("CandidatoComSituacaoInvalidaParaConvocacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A convocação não pode ser desfeita pois o candidato já foi exportado..
        /// </summary>
        public static string ConvocacaoNaoPodeSerDesfeitaException {
            get {
                return ResourceManager.GetString("ConvocacaoNaoPodeSerDesfeitaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A convocação não pode ser alterada para candidatos que já foram exportados..
        /// </summary>
        public static string ConvocadoExportadoException {
            get {
                return ResourceManager.GetString("ConvocadoExportadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe etapa de seleção ativa para este processo. Não é possível desfazer o lançamento de resultado..
        /// </summary>
        public static string DesfazerLancamentoEtapaInvalidaException {
            get {
                return ResourceManager.GetString("DesfazerLancamentoEtapaInvalidaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida. Existem candidatos que ainda não tiveram resultado lançado ou que já foram convocados..
        /// </summary>
        public static string DesfazerLancamentoException {
            get {
                return ResourceManager.GetString("DesfazerLancamentoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida. Este candidato ainda não teve resultado lançado ou já foi convocado..
        /// </summary>
        public static string DesfazerLancamentosException {
            get {
                return ResourceManager.GetString("DesfazerLancamentosException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma do % Bolsa com o % Financiamento não pode ultrapassar o Percentual Máximo de Bolsa calculado, exceto se o Percentual Máximo de Bolsa for menor 50%. Neste caso, é permitido um lançamento único de até 50% de financiamento..
        /// </summary>
        public static string LancamentoBolsaUltrapassaLimiteComExcecaoException {
            get {
                return ResourceManager.GetString("LancamentoBolsaUltrapassaLimiteComExcecaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma do % Bolsa com o % Financiamento não pode ultrapassar o Percentual Máximo de Bolsa calculado..
        /// </summary>
        public static string LancamentoBolsaUltrapassaLimiteException {
            get {
                return ResourceManager.GetString("LancamentoBolsaUltrapassaLimiteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um candidato com a classificação {0}..
        /// </summary>
        public static string LancamentoNotaClassificacaoDuplicadaException {
            get {
                return ResourceManager.GetString("LancamentoNotaClassificacaoDuplicadaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A convocação só pode ser realizada para candidatos que estão na mesma situação..
        /// </summary>
        public static string MultiplasSituacoesParaConvocacaoException {
            get {
                return ResourceManager.GetString("MultiplasSituacoesParaConvocacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O % Bolsa não pode ultrapassar o Percentual Máximo de Bolsa calculado..
        /// </summary>
        public static string PercentualBolsaUltrapassaPercentualMaximoException {
            get {
                return ResourceManager.GetString("PercentualBolsaUltrapassaPercentualMaximoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos com a situação {0} não podem ter lançamento desfeito..
        /// </summary>
        public static string SituacaoNaoPermiteDesfazerLancamentoException {
            get {
                return ResourceManager.GetString("SituacaoNaoPermiteDesfazerLancamentoException", resourceCulture);
            }
        }
    }
}
