//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.Processo.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.Processo.App_LocalResources.MetadataResour" +
                            "ce", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo do documento.
        /// </summary>
        public static string ArquivoModelo {
            get {
                return ResourceManager.GetString("ArquivoModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinatura Digital.
        /// </summary>
        public static string AssinaturaDigital_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("AssinaturaDigital_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinatura eletrônica?.
        /// </summary>
        public static string AssinaturaEletronica {
            get {
                return ResourceManager.GetString("AssinaturaEletronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string AssinaturaEletronica_FALSE {
            get {
                return ResourceManager.GetString("AssinaturaEletronica_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string AssinaturaEletronica_TRUE {
            get {
                return ResourceManager.GetString("AssinaturaEletronica_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string CabecalhoProcessoViewModel_Descricao {
            get {
                return ResourceManager.GetString("CabecalhoProcessoViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo processo.
        /// </summary>
        public static string CabecalhoProcessoViewModel_DescricaoTipoProcesso {
            get {
                return ResourceManager.GetString("CabecalhoProcessoViewModel_DescricaoTipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento SAE.
        /// </summary>
        public static string CodigoEventoSAE {
            get {
                return ResourceManager.GetString("CodigoEventoSAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ConfiguracoesFormularioViewModel_DisponivelApenasComCheckin_FALSE {
            get {
                return ResourceManager.GetString("ConfiguracoesFormularioViewModel_DisponivelApenasComCheckin_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ConfiguracoesFormularioViewModel_DisponivelApenasComCheckin_TRUE {
            get {
                return ResourceManager.GetString("ConfiguracoesFormularioViewModel_DisponivelApenasComCheckin_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem do formulário.
        /// </summary>
        public static string ConfiguracoesFormularioViewModel_Mensagem {
            get {
                return ResourceManager.GetString("ConfiguracoesFormularioViewModel_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ConfiguracoesModeloDocumentoViewModel_ExibeDocumentoHome_FALSE {
            get {
                return ResourceManager.GetString("ConfiguracoesModeloDocumentoViewModel_ExibeDocumentoHome_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ConfiguracoesModeloDocumentoViewModel_ExibeDocumentoHome_TRUE {
            get {
                return ResourceManager.GetString("ConfiguracoesModeloDocumentoViewModel_ExibeDocumentoHome_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar Configurações?.
        /// </summary>
        public static string CopiaEtapaProcesso_CopiarConfiguracoes {
            get {
                return ResourceManager.GetString("CopiaEtapaProcesso_CopiarConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string CopiaEtapaProcesso_CopiarConfiguracoes_FALSE {
            get {
                return ResourceManager.GetString("CopiaEtapaProcesso_CopiarConfiguracoes_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string CopiaEtapaProcesso_CopiarConfiguracoes_TRUE {
            get {
                return ResourceManager.GetString("CopiaEtapaProcesso_CopiarConfiguracoes_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano Referência.
        /// </summary>
        public static string CopiaProcessoViewModel_CopiaAnoReferencia {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_CopiaAnoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string CopiaProcessoViewModel_CopiaDescricao {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_CopiaDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário do Evento.
        /// </summary>
        public static string CopiaProcessoViewModel_CopiarFormularioEvento {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_CopiarFormularioEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarquia de Oferta / Grupo de Ofertas.
        /// </summary>
        public static string CopiaProcessoViewModel_CopiarItens {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_CopiarItens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string CopiaProcessoViewModel_CopiarNotificacoes {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_CopiarNotificacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre Referência.
        /// </summary>
        public static string CopiaProcessoViewModel_CopiaSemestreReferencia {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_CopiaSemestreReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim inscrição.
        /// </summary>
        public static string CopiaProcessoViewModel_DataFimInscricao {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_DataFimInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string CopiaProcessoViewModel_DataInicio {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início inscrição.
        /// </summary>
        public static string CopiaProcessoViewModel_DataInicioInscricao {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_DataInicioInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo de origem.
        /// </summary>
        public static string CopiaProcessoViewModel_Descricao {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo origem.
        /// </summary>
        public static string CopiaProcessoViewModel_DescricaoTipoProcesso {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_DescricaoTipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano Referência.
        /// </summary>
        public static string CopiaProcessoViewModel_NovoProcessoAnoReferencia {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_NovoProcessoAnoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string CopiaProcessoViewModel_NovoProcessoDescricao {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_NovoProcessoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre Referência.
        /// </summary>
        public static string CopiaProcessoViewModel_NovoProcessoSemestreReferencia {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_NovoProcessoSemestreReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve estar entre {0} e {1}.
        /// </summary>
        public static string CopiaProcessoViewModel_NovoProcessoSemestreReferencia_ValueRange {
            get {
                return ResourceManager.GetString("CopiaProcessoViewModel_NovoProcessoSemestreReferencia_ValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final na home.
        /// </summary>
        public static string DataFimDocumentoHome {
            get {
                return ResourceManager.GetString("DataFimDocumentoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim do evento.
        /// </summary>
        public static string DataFimEvento {
            get {
                return ResourceManager.GetString("DataFimEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim para respostas.
        /// </summary>
        public static string DataFimFormulario {
            get {
                return ResourceManager.GetString("DataFimFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início das atividades.
        /// </summary>
        public static string DataInicioAtividade {
            get {
                return ResourceManager.GetString("DataInicioAtividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial na home.
        /// </summary>
        public static string DataInicioDocumentoHome {
            get {
                return ResourceManager.GetString("DataInicioDocumentoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início do evento.
        /// </summary>
        public static string DataInicioEvento {
            get {
                return ResourceManager.GetString("DataInicioEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início para respostas.
        /// </summary>
        public static string DataInicioFormulario {
            get {
                return ResourceManager.GetString("DataInicioFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requer check-in?.
        /// </summary>
        public static string DisponivelApenasComCheckin {
            get {
                return ResourceManager.GetString("DisponivelApenasComCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em processos que possuem gestão de eventos e taxa associada, o Evento SAE deve ser informado, para o controle orçamentário das receitas..
        /// </summary>
        public static string ERR_ProcessoPossuiTaxaENaoPossuiEventoSaeException {
            get {
                return ResourceManager.GetString("ERR_ProcessoPossuiTaxaENaoPossuiEventoSaeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir na home?.
        /// </summary>
        public static string ExibeDocumentoHome {
            get {
                return ResourceManager.GetString("ExibeDocumentoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período para abertura do check-in.
        /// </summary>
        public static string HoraAberturaCheckin {
            get {
                return ResourceManager.GetString("HoraAberturaCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do formulário.
        /// </summary>
        public static string NomeFormulario {
            get {
                return ResourceManager.GetString("NomeFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID inválido.
        /// </summary>
        public static string ProcessoFiltroViewModel_Seq_MaxValue {
            get {
                return ResourceManager.GetString("ProcessoFiltroViewModel_Seq_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório em eventos que possuem taxa, para o controle orçamentário das receitas..
        /// </summary>
        public static string ProcessoViewModel_CodigoEventoSAE_FillInstructions {
            get {
                return ResourceManager.GetString("ProcessoViewModel_CodigoEventoSAE_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlar vagas na inscrição.
        /// </summary>
        public static string ProcessoViewModel_ControlaVagaInscricao {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ControlaVagaInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ProcessoViewModel_ControlaVagaInscricao_FALSE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ControlaVagaInscricao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ProcessoViewModel_ControlaVagaInscricao_TRUE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ControlaVagaInscricao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta data é utilizada na emissão do documento e pode indicar, por
        ///exemplo, a data de início das aulas do aluno ou docente..
        /// </summary>
        public static string ProcessoViewModel_DataInicioAtividade_FillInstructions {
            get {
                return ResourceManager.GetString("ProcessoViewModel_DataInicioAtividade_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string ProcessoViewModel_Descricao {
            get {
                return ResourceManager.GetString("ProcessoViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir a hierarquia de ofertas fechada.
        /// </summary>
        public static string ProcessoViewModel_ExibeArvoreFechada {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ExibeArvoreFechada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ProcessoViewModel_ExibeArvoreFechada_FALSE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ExibeArvoreFechada_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ProcessoViewModel_ExibeArvoreFechada_TRUE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ExibeArvoreFechada_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir período da atividade na oferta?.
        /// </summary>
        public static string ProcessoViewModel_ExibirPeriodoAtividadeOferta {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ExibirPeriodoAtividadeOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ProcessoViewModel_ExibirPeriodoAtividadeOferta_FALSE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ExibirPeriodoAtividadeOferta_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ProcessoViewModel_ExibirPeriodoAtividadeOferta_TRUE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_ExibirPeriodoAtividadeOferta_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a quantidade de horas/minutos para iniciar o atendimento do check-in, antes do início das atividades. Os valores devem estar entre 00:00 e 23:59..
        /// </summary>
        public static string ProcessoViewModel_HoraAberturaCheckin_FillInstructions {
            get {
                return ResourceManager.GetString("ProcessoViewModel_HoraAberturaCheckin_FillInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link para o processo:.
        /// </summary>
        public static string ProcessoViewModel_LinkProcesso {
            get {
                return ResourceManager.GetString("ProcessoViewModel_LinkProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de inscrições por inscrito.
        /// </summary>
        public static string ProcessoViewModel_MaximoInscricoesPorInscrito {
            get {
                return ResourceManager.GetString("ProcessoViewModel_MaximoInscricoesPorInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser maior ou igual a {0}.
        /// </summary>
        public static string ProcessoViewModel_MaximoInscricoesPorInscrito_MinValue {
            get {
                return ResourceManager.GetString("ProcessoViewModel_MaximoInscricoesPorInscrito_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de ofertas por inscrição.
        /// </summary>
        public static string ProcessoViewModel_MaximoOfertaPorInscricao {
            get {
                return ResourceManager.GetString("ProcessoViewModel_MaximoOfertaPorInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser maior ou igual a {0}.
        /// </summary>
        public static string ProcessoViewModel_MaximoOfertaPorInscricao_MinValue {
            get {
                return ResourceManager.GetString("ProcessoViewModel_MaximoOfertaPorInscricao_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de opções por inscrição.
        /// </summary>
        public static string ProcessoViewModel_MaximoOpcoesOfertaPorInscricao {
            get {
                return ResourceManager.GetString("ProcessoViewModel_MaximoOpcoesOfertaPorInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser maior ou igual a {0}.
        /// </summary>
        public static string ProcessoViewModel_MaximoOpcoesOfertaPorInscricao_MinValue {
            get {
                return ResourceManager.GetString("ProcessoViewModel_MaximoOpcoesOfertaPorInscricao_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento financeiro.
        /// </summary>
        public static string ProcessoViewModel_SeqEvento {
            get {
                return ResourceManager.GetString("ProcessoViewModel_SeqEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template de processo.
        /// </summary>
        public static string ProcessoViewModel_SeqTemplateProcessoSGF {
            get {
                return ResourceManager.GetString("ProcessoViewModel_SeqTemplateProcessoSGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de hierarquia de ofertas.
        /// </summary>
        public static string ProcessoViewModel_SeqTipoHierarquiaOferta {
            get {
                return ResourceManager.GetString("ProcessoViewModel_SeqTipoHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identidade visual.
        /// </summary>
        public static string ProcessoViewModel_SeqUnidadeResponsavelTipoProcessoIdVisual {
            get {
                return ResourceManager.GetString("ProcessoViewModel_SeqUnidadeResponsavelTipoProcessoIdVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ProcessoViewModel_VerificaCoincidenciaHorario_FALSE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_VerificaCoincidenciaHorario_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ProcessoViewModel_VerificaCoincidenciaHorario_TRUE {
            get {
                return ResourceManager.GetString("ProcessoViewModel_VerificaCoincidenciaHorario_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requer check-in?.
        /// </summary>
        public static string RequerCheckin {
            get {
                return ResourceManager.GetString("RequerCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string RequerCheckin_FALSE {
            get {
                return ResourceManager.GetString("RequerCheckin_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string RequerCheckin_TRUE {
            get {
                return ResourceManager.GetString("RequerCheckin_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário.
        /// </summary>
        public static string SeqFormularioSgf {
            get {
                return ResourceManager.GetString("SeqFormularioSgf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        public static string SeqTipoDocumento {
            get {
                return ResourceManager.GetString("SeqTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de formulário.
        /// </summary>
        public static string SeqTipoFormularioSgf {
            get {
                return ResourceManager.GetString("SeqTipoFormularioSgf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visão do formulário.
        /// </summary>
        public static string SeqVisaoSgf {
            get {
                return ResourceManager.GetString("SeqVisaoSgf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobrar por oferta?.
        /// </summary>
        public static string TaxaProcessoViewModel_CobrarPorOferta {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_CobrarPorOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string TaxaProcessoViewModel_CobrarPorOferta_FALSE {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_CobrarPorOferta_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string TaxaProcessoViewModel_CobrarPorOferta_TRUE {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_CobrarPorOferta_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição complementar.
        /// </summary>
        public static string TaxaProcessoViewModel_DescricaoComplementar {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_DescricaoComplementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite seleção na inscrição?.
        /// </summary>
        public static string TaxaProcessoViewModel_SelecaoInscricao {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_SelecaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string TaxaProcessoViewModel_SelecaoInscricao_FALSE {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_SelecaoInscricao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string TaxaProcessoViewModel_SelecaoInscricao_TRUE {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_SelecaoInscricao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de taxa.
        /// </summary>
        public static string TaxaProcessoViewModel_SeqTipoTaxa {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_SeqTipoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de cobrança.
        /// </summary>
        public static string TaxaProcessoViewModel_TipoCobranca {
            get {
                return ResourceManager.GetString("TaxaProcessoViewModel_TipoCobranca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config. de assinatura GAD.
        /// </summary>
        public static string TokenConfiguracaoDocumentoGad {
            get {
                return ResourceManager.GetString("TokenConfiguracaoDocumentoGad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar coincidência de horários?.
        /// </summary>
        public static string VerificaCoincidenciaHorario {
            get {
                return ResourceManager.GetString("VerificaCoincidenciaHorario", resourceCulture);
            }
        }
    }
}
