//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.Processo.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.Processo.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_AssociacaoEtapa {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_AssociacaoEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_AssociacaoEtapa_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_AssociacaoEtapa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_ConfigurarNotificacao {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_ConfigurarNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_ConfigurarNotificacao_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_ConfigurarNotificacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_Editar {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_Editar_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_Editar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de ofertas.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_GrupoOferta {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_GrupoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de ofertas.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_GrupoOferta_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_GrupoOferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de taxas.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_GrupoTaxa {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_GrupoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de taxas.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_GrupoTaxa_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_GrupoTaxa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarquia de oferta.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_HierarquiaOferta {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_HierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarquia de oferta.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_HierarquiaOferta_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_HierarquiaOferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão de Inscrição Fora do Prazo.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_InscricaoForaPrazo {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_InscricaoForaPrazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão de Inscrição Fora do Prazo.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_InscricaoForaPrazo_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_InscricaoForaPrazo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período taxa em lote.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_TaxaOfertaLote {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_TaxaOfertaLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período taxa em lote.
        /// </summary>
        public static string _BotaoConfigurarProcesso_Botao_TaxaOfertaLote_Tooltip {
            get {
                return ResourceManager.GetString("_BotaoConfigurarProcesso_Botao_TaxaOfertaLote_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo endereço eletrônico.
        /// </summary>
        public static string _DadosContatoProcesso_Botao_Insert_EnderecosEletronicos {
            get {
                return ResourceManager.GetString("_DadosContatoProcesso_Botao_Insert_EnderecosEletronicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo endereço eletrônico.
        /// </summary>
        public static string _DadosContatoProcesso_Botao_Insert_EnderecosEletronicos_Tooltip {
            get {
                return ResourceManager.GetString("_DadosContatoProcesso_Botao_Insert_EnderecosEletronicos_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Telefone.
        /// </summary>
        public static string _DadosContatoProcesso_Botao_Insert_Telefones {
            get {
                return ResourceManager.GetString("_DadosContatoProcesso_Botao_Insert_Telefones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Telefone.
        /// </summary>
        public static string _DadosContatoProcesso_Botao_Insert_Telefones_Tooltip {
            get {
                return ResourceManager.GetString("_DadosContatoProcesso_Botao_Insert_Telefones_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos do Cadastro do Inscrito.
        /// </summary>
        public static string _EditarProcesso_Aba_Title_tabCamposCadastroInscrito {
            get {
                return ResourceManager.GetString("_EditarProcesso_Aba_Title_tabCamposCadastroInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do contato.
        /// </summary>
        public static string _EditarProcesso_Aba_Title_tabDadosContato {
            get {
                return ResourceManager.GetString("_EditarProcesso_Aba_Title_tabDadosContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        public static string _EditarProcesso_Aba_Title_tabDadosEvento {
            get {
                return ResourceManager.GetString("_EditarProcesso_Aba_Title_tabDadosEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do processo.
        /// </summary>
        public static string _EditarProcesso_Aba_Title_tabDadosProcesso {
            get {
                return ResourceManager.GetString("_EditarProcesso_Aba_Title_tabDadosProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas.
        /// </summary>
        public static string _EditarProcesso_Aba_Title_tabDadosTaxas {
            get {
                return ResourceManager.GetString("_EditarProcesso_Aba_Title_tabDadosTaxas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova taxa.
        /// </summary>
        public static string _EditarProcesso_Botao_Insert_Taxas {
            get {
                return ResourceManager.GetString("_EditarProcesso_Botao_Insert_Taxas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova taxa.
        /// </summary>
        public static string _EditarProcesso_Botao_Insert_Taxas_Tooltip {
            get {
                return ResourceManager.GetString("_EditarProcesso_Botao_Insert_Taxas_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo idioma.
        /// </summary>
        public static string _EditarProcesso_Botao_Open {
            get {
                return ResourceManager.GetString("_EditarProcesso_Botao_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo idioma.
        /// </summary>
        public static string _EditarProcesso_Botao_Open_Tooltip {
            get {
                return ResourceManager.GetString("_EditarProcesso_Botao_Open_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string _EditarProcesso_Botao_Salvar {
            get {
                return ResourceManager.GetString("_EditarProcesso_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string _EditarProcesso_Botao_Salvar_Tooltip {
            get {
                return ResourceManager.GetString("_EditarProcesso_Botao_Salvar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string _ListarProcesso_Botao_Configurarnotificacao {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_Configurarnotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string _ListarProcesso_Botao_Configurarnotificacao_Tooltip {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_Configurarnotificacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cópia de Processo.
        /// </summary>
        public static string _ListarProcesso_Botao_CopiarProcesso {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_CopiarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cópia de Processo.
        /// </summary>
        public static string _ListarProcesso_Botao_CopiarProcesso_Tooltip {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_CopiarProcesso_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão de Inscrição Fora do Prazo.
        /// </summary>
        public static string _ListarProcesso_Botao_Inscricaoforaprazo {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_Inscricaoforaprazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão de Inscrição Fora do Prazo.
        /// </summary>
        public static string _ListarProcesso_Botao_Inscricaoforaprazo_Tooltip {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_Inscricaoforaprazo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenação.
        /// </summary>
        public static string _ListarProcesso_Botao_Open_Tooltip {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_Open_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período taxa em lote.
        /// </summary>
        public static string _ListarProcesso_Botao_Taxasoferta {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_Taxasoferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período taxa em lote.
        /// </summary>
        public static string _ListarProcesso_Botao_Taxasoferta_Tooltip {
            get {
                return ResourceManager.GetString("_ListarProcesso_Botao_Taxasoferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do processo &quot;{0}&quot;?.
        /// </summary>
        public static string _ListarProcesso_Exclusao_Processo_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarProcesso_Exclusao_Processo_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Processo.
        /// </summary>
        public static string _ListarProcesso_Exclusao_Processo_Title {
            get {
                return ResourceManager.GetString("_ListarProcesso_Exclusao_Processo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos.
        /// </summary>
        public static string _ListarProcesso_gridProcesso_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarProcesso_gridProcesso_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos e Formulários.
        /// </summary>
        public static string Aba_Title_tabDocumentosEFormularios {
            get {
                return ResourceManager.GetString("Aba_Title_tabDocumentosEFormularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se existir oferta no processo com a(s) taxa(s) {0} cadastrada(s), esta operação apagará os valores da quantidade mínima e máxima dessa(s) taxa(s), deseja continuar?.
        /// </summary>
        public static string Assert_AlteracaoCobrancaOfertaOutroTipoParaQuantidadeOferta {
            get {
                return ResourceManager.GetString("Assert_AlteracaoCobrancaOfertaOutroTipoParaQuantidadeOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se existirem ofertas no processo com a(s) taxa(s) &quot;{0}&quot; cadastradas, esta operação apagará os valores das quantidades mínima e máxima dessa taxa, que precisarão ser configurados novamente. Deseja continuar?.
        /// </summary>
        public static string Assert_AlteracaoCobrancaOfertaQuantidadeOfertaParaOutroTipo {
            get {
                return ResourceManager.GetString("Assert_AlteracaoCobrancaOfertaQuantidadeOfertaParaOutroTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existem documentos emitidos com configuração de assinatura do GAD. Deseja confirmar a alteração?.
        /// </summary>
        public static string Assert_DocumentosEmitidosAssociados {
            get {
                return ResourceManager.GetString("Assert_DocumentosEmitidosAssociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições com este formulário preenchido. A troca do formulário se aplicará somente às novas inscrições. As inscrições que já responderam o formulário permanecerão com a versão anterior. Deseja continuar?.
        /// </summary>
        public static string Assert_InscricoesValidasFormularioPreenchido {
            get {
                return ResourceManager.GetString("Assert_InscricoesValidasFormularioPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Botao_Associacaoetapa {
            get {
                return ResourceManager.GetString("Botao_Associacaoetapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Botao_Associacaoetapa_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Associacaoetapa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração de páginas da etapa.
        /// </summary>
        public static string Botao_Configuracaopaginaetapa {
            get {
                return ResourceManager.GetString("Botao_Configuracaopaginaetapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração de páginas da etapa.
        /// </summary>
        public static string Botao_Configuracaopaginaetapa_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Configuracaopaginaetapa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação requerida.
        /// </summary>
        public static string Botao_Documentacaorequerida {
            get {
                return ResourceManager.GetString("Botao_Documentacaorequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação requerida.
        /// </summary>
        public static string Botao_Documentacaorequerida_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Documentacaorequerida_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar idioma.
        /// </summary>
        public static string Botao_Editar {
            get {
                return ResourceManager.GetString("Botao_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de documentação requerida.
        /// </summary>
        public static string Botao_Grupodocumentacaorequerida {
            get {
                return ResourceManager.GetString("Botao_Grupodocumentacaorequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de documentação requerida.
        /// </summary>
        public static string Botao_Grupodocumentacaorequerida_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Grupodocumentacaorequerida_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de ofertas.
        /// </summary>
        public static string Botao_Grupooferta {
            get {
                return ResourceManager.GetString("Botao_Grupooferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de ofertas.
        /// </summary>
        public static string Botao_Grupooferta_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Grupooferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de taxas.
        /// </summary>
        public static string Botao_Grupootaxa_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Grupootaxa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de taxas.
        /// </summary>
        public static string Botao_Grupotaxa {
            get {
                return ResourceManager.GetString("Botao_Grupotaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarquia de oferta.
        /// </summary>
        public static string Botao_Hierarquiaoferta {
            get {
                return ResourceManager.GetString("Botao_Hierarquiaoferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarquia de oferta.
        /// </summary>
        public static string Botao_Hierarquiaoferta_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Hierarquiaoferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir código de autorização.
        /// </summary>
        public static string Botao_Insert_CodigosAutorizacao_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Insert_CodigosAutorizacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string Botao_Notificacoes {
            get {
                return ResourceManager.GetString("Botao_Notificacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string Botao_Notificacoes_tooltip {
            get {
                return ResourceManager.GetString("Botao_Notificacoes_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulários do Evento.
        /// </summary>
        public static string ConfiguracoesFormulario_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("ConfiguracoesFormulario_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração de Emissão de Documentos.
        /// </summary>
        public static string ConfiguracoesModeloDocumento_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("ConfiguracoesModeloDocumento_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Copia_Processo_Botao_Cancelar_Tooltip {
            get {
                return ResourceManager.GetString("Copia_Processo_Botao_Cancelar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string Copia_Processo_Botao_Copiar_Tooltip {
            get {
                return ResourceManager.GetString("Copia_Processo_Botao_Copiar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas a serem copiadas.
        /// </summary>
        public static string CopiarProcesso_copiaEtapas_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("CopiarProcesso_copiaEtapas_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens a serem copiados.
        /// </summary>
        public static string CopiarProcesso_copiaItens_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("CopiarProcesso_copiaItens_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string CopiarProcesso_copiaProcessoDestino_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("CopiarProcesso_copiaProcessoDestino_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        public static string CopiarProcesso_copiaProcessoOrigem_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("CopiarProcesso_copiaProcessoOrigem_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As datas início e fim da etapa serão replicadas para as ofertas..
        /// </summary>
        public static string CopiarProcesso_Label_MensagemInformativa {
            get {
                return ResourceManager.GetString("CopiarProcesso_Label_MensagemInformativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Processo.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços Eletrônicos.
        /// </summary>
        public static string EnderecosEletronicos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("EnderecosEletronicos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string Idiomas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Idiomas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar idioma.
        /// </summary>
        public static string Idiomas_Modal_Editar_Titulo {
            get {
                return ResourceManager.GetString("Idiomas_Modal_Editar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Processo.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo processo.
        /// </summary>
        public static string Index_Botao_Novo {
            get {
                return ResourceManager.GetString("Index_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Index_Copia_Processo_Botao_Cancelar {
            get {
                return ResourceManager.GetString("Index_Copia_Processo_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string Index_Copia_Processo_Botao_Copiar {
            get {
                return ResourceManager.GetString("Index_Copia_Processo_Botao_Copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a cópia do processo selecionado?.
        /// </summary>
        public static string Index_Copia_Processo_Confirmacao_Mensagem {
            get {
                return ResourceManager.GetString("Index_Copia_Processo_Confirmacao_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Cópia.
        /// </summary>
        public static string Index_Copia_Processo_Confirmacao_Titulo {
            get {
                return ResourceManager.GetString("Index_Copia_Processo_Confirmacao_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cópia de Processo.
        /// </summary>
        public static string Index_Copiar_Processo {
            get {
                return ResourceManager.GetString("Index_Copiar_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Processo.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unidade responsável, o tipo de processo, o ano e o semestre de referência não podem ser alterados, porque este processo possui integração com outro sistema..
        /// </summary>
        public static string Label_PossuiIntegracao {
            get {
                return ResourceManager.GetString("Label_PossuiIntegracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O template de processo do processo de origem está desativado, portanto, as etapas não poderão ser copiadas..
        /// </summary>
        public static string Mensagem_Copia_Processo_Template_Desativado {
            get {
                return ResourceManager.GetString("Mensagem_Copia_Processo_Template_Desativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de processo do processo de origem selecionado está desativado, portanto, a hierarquia de ofertas, com seus grupos de oferta, e as etapas não poderão ser copiados..
        /// </summary>
        public static string Mensagem_Copia_Processo_Tipo_Desativado {
            get {
                return ResourceManager.GetString("Mensagem_Copia_Processo_Tipo_Desativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de hierarquia do processo de origem selecionado está desativado, portanto, a hierarquia de oferta, com seus grupos de oferta não poderão ser copiados..
        /// </summary>
        public static string Mensagem_Copia_Processo_Tipo_Hierarquia_Desativada {
            get {
                return ResourceManager.GetString("Mensagem_Copia_Processo_Tipo_Hierarquia_Desativada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marque abaixo os campos que deverão estar visíveis na tela de Cadastro do Inscrito durante a inscrição. Os campos de visibilidade obrigatória para o tipo de processo informado serão marcados por padrão e não poderão ser desmarcados..
        /// </summary>
        public static string MensagemInformativaCamposInscrito {
            get {
                return ResourceManager.GetString("MensagemInformativaCamposInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Idioma.
        /// </summary>
        public static string Modal_Editar_Titulo {
            get {
                return ResourceManager.GetString("Modal_Editar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Idioma.
        /// </summary>
        public static string Modal_Inserir_Titulo {
            get {
                return ResourceManager.GetString("Modal_Inserir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas.
        /// </summary>
        public static string Taxas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Taxas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas.
        /// </summary>
        public static string TaxasDetalhe_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("TaxasDetalhe_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones.
        /// </summary>
        public static string Telefones_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Telefones_Detalhe_Titulo", resourceCulture);
            }
        }
    }
}
