//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.RES.Views.Cliente.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.RES.Views.Cliente.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string _ListarCliente_gridCliente_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarCliente_gridCliente_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo endereço.
        /// </summary>
        public static string Botao_Insert_Endereco {
            get {
                return ResourceManager.GetString("Botao_Insert_Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo endereço.
        /// </summary>
        public static string Botao_Insert_Endereco_Enderecos {
            get {
                return ResourceManager.GetString("Botao_Insert_Endereco_Enderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo endereço eletrônico.
        /// </summary>
        public static string Botao_Insert_EnderecosEletronicos {
            get {
                return ResourceManager.GetString("Botao_Insert_EnderecosEletronicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo endereço eletrônico.
        /// </summary>
        public static string Botao_Insert_EnderecosEletronicos_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Insert_EnderecosEletronicos_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo telefone.
        /// </summary>
        public static string Botao_Insert_Telefones_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Insert_Telefones_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo telefone.
        /// </summary>
        public static string Botao_Insert_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Insert_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Cliente.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços.
        /// </summary>
        public static string Enderecos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Enderecos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços Eletrônicos.
        /// </summary>
        public static string EnderecosEletronicos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("EnderecosEletronicos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do cliente &quot;{0}&quot;?.
        /// </summary>
        public static string Exclusao_Cliente_Confirmacao {
            get {
                return ResourceManager.GetString("Exclusao_Cliente_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Cliente.
        /// </summary>
        public static string Exclusao_Cliente_Title {
            get {
                return ResourceManager.GetString("Exclusao_Cliente_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string gridCliente_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridCliente_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Cliente.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo cliente.
        /// </summary>
        public static string Index_Botao_Novo {
            get {
                return ResourceManager.GetString("Index_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo cliente.
        /// </summary>
        public static string Index_Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Index_Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Cliente.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones.
        /// </summary>
        public static string Telefones_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Telefones_Detalhe_Titulo", resourceCulture);
            }
        }
    }
}
