//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.GrupoOferta.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.GrupoOferta.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Grupo de Ofertas.
        /// </summary>
        public static string _EditarConfiguracaoEtapa_GruposOfertaDetalhe_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_EditarConfiguracaoEtapa_GruposOfertaDetalhe_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar item.
        /// </summary>
        public static string _EditarGrupoOferta_DataSelector_Botao_Abrir {
            get {
                return ResourceManager.GetString("_EditarGrupoOferta_DataSelector_Botao_Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar item.
        /// </summary>
        public static string _EditarGrupoOferta_DataSelector_Botao_Abrir_Tooltip {
            get {
                return ResourceManager.GetString("_EditarGrupoOferta_DataSelector_Botao_Abrir_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens do Grupo de Oferta.
        /// </summary>
        public static string _EditarGrupoOferta_fieldsetItensGrupoOferta_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("_EditarGrupoOferta_fieldsetItensGrupoOferta_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo grupo.
        /// </summary>
        public static string _FiltrarGrupoOferta_Botao_Novo {
            get {
                return ResourceManager.GetString("_FiltrarGrupoOferta_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do grupo de ofertas &quot;{0}“?.
        /// </summary>
        public static string _ListarGrupoOferta_Exclusao_Grupo_Oferta_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarGrupoOferta_Exclusao_Grupo_Oferta_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Grupo de Ofertas.
        /// </summary>
        public static string _ListarGrupoOferta_Exclusao_Grupo_Oferta_Title {
            get {
                return ResourceManager.GetString("_ListarGrupoOferta_Exclusao_Grupo_Oferta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos de Oferta.
        /// </summary>
        public static string _ListarGrupoOferta_gridGrupoOferta_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarGrupoOferta_gridGrupoOferta_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar grupo de ofertas.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços Eletrônicos.
        /// </summary>
        public static string EnderecosEletronicos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("EnderecosEletronicos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo grupo de ofertas.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo grupo de ofertas.
        /// </summary>
        public static string Index_Botao_Novo {
            get {
                return ResourceManager.GetString("Index_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Grupo de Ofertas.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem ofertas que atualmente estão associadas a outro grupo. Ao salvar, elas serão desassociadas do grupo atual e associadas ao grupo &apos;{0}&apos;. Deseja continuar?.
        /// </summary>
        public static string Mensagem_Confirma_Alteracao {
            get {
                return ResourceManager.GetString("Mensagem_Confirma_Alteracao", resourceCulture);
            }
        }
    }
}
