//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.DocumentoRequerido.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.DocumentoRequerido.App_LocalResources.UIRe" +
                            "source", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatória?.
        /// </summary>
        public static string _EditarDocumentoRequerido_fieldsetObrigatoriaDocumentacaoRequerida_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("_EditarDocumentoRequerido_fieldsetObrigatoriaDocumentacaoRequerida_Fieldset_Legen" +
                        "da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentações Requeridas.
        /// </summary>
        public static string _ListarDocumentosRequeridos_gridDocumentacaoRequerida_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarDocumentosRequeridos_gridDocumentacaoRequerida_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições com documento cadastrado. A exclusão deste documento requerido excluirá o documento vinculado ao candidato e seu anexo. Deseja continuar?.
        /// </summary>
        public static string Assert_ExclusaoDocumentoRequerido {
            get {
                return ResourceManager.GetString("Assert_ExclusaoDocumentoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições com documento cadastrado. A exclusão deste documento requerido excluirá o documento vinculado ao candidato e seu anexo, se existir. Deseja continuar?.
        /// </summary>
        public static string Assert_ExclusaoDocumentoRequeridoSeExistir {
            get {
                return ResourceManager.GetString("Assert_ExclusaoDocumentoRequeridoSeExistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições com documentação cadastrada. Caso exista arquivo anexado para o documento alterado, o candidato não terá como trocá-lo. Deseja continuar?.
        /// </summary>
        public static string Assert_ModificaTipoDocumento {
            get {
                return ResourceManager.GetString("Assert_ModificaTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições que já fizeram o upload de documentos e não poderão anexar um arquivo para este novo documento. Deseja continuar?.
        /// </summary>
        public static string Assert_ModificaUpload {
            get {
                return ResourceManager.GetString("Assert_ModificaUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições com este documento cadastrado com a versão “Cópia Simples”. A alteração versão deixará essa informação incompatível. Deseja continuar?.
        /// </summary>
        public static string Assert_ModificaVersaoDocumento {
            get {
                return ResourceManager.GetString("Assert_ModificaVersaoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação requerida.
        /// </summary>
        public static string Botao_Documentacaorequerida {
            get {
                return ResourceManager.GetString("Botao_Documentacaorequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação requerida.
        /// </summary>
        public static string Botao_Documentacaorequerida_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Documentacaorequerida_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Documentação Requerida.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da documentação requerida &quot;{0}&quot;?.
        /// </summary>
        public static string Exclusao_Documentacao_Requerida_Confirmacao {
            get {
                return ResourceManager.GetString("Exclusao_Documentacao_Requerida_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Documentação Requerida.
        /// </summary>
        public static string Exclusao_Documentacao_Requerida_Title {
            get {
                return ResourceManager.GetString("Exclusao_Documentacao_Requerida_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Documentação Requerida.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova documentação requerida.
        /// </summary>
        public static string Index_Botao_Novo {
            get {
                return ResourceManager.GetString("Index_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova documentação requerida.
        /// </summary>
        public static string Index_Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Index_Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Documentação Requerida.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
    }
}
