//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.AcompanhamentoInscrito.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.AcompanhamentoInscrito.App_LocalResources." +
                            "UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Dados do Inscrito.
        /// </summary>
        public static string _DetailList_AlterarDados_Modal_Titulo {
            get {
                return ResourceManager.GetString("_DetailList_AlterarDados_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Situação.
        /// </summary>
        public static string _DetailList_AlterarSituacaoLote_Modal_Titulo {
            get {
                return ResourceManager.GetString("_DetailList_AlterarSituacaoLote_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar dados do inscrito.
        /// </summary>
        public static string _DetailList_Botao_AlterarDados {
            get {
                return ResourceManager.GetString("_DetailList_Botao_AlterarDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar dados do inscrito.
        /// </summary>
        public static string _DetailList_Botao_AlterarDados_Tooltip {
            get {
                return ResourceManager.GetString("_DetailList_Botao_AlterarDados_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar situação da inscrição.
        /// </summary>
        public static string _DetailList_Botao_AlterarSituacaoInscricao {
            get {
                return ResourceManager.GetString("_DetailList_Botao_AlterarSituacaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Situação.
        /// </summary>
        public static string _DetailList_Botao_AlterarSituacaoInscricao_Tooltip {
            get {
                return ResourceManager.GetString("_DetailList_Botao_AlterarSituacaoInscricao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar inscrição.
        /// </summary>
        public static string _DetailList_Botao_Consultainscricao {
            get {
                return ResourceManager.GetString("_DetailList_Botao_Consultainscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar inscrição.
        /// </summary>
        public static string _DetailList_Botao_Consultainscricao_Tooltip {
            get {
                return ResourceManager.GetString("_DetailList_Botao_Consultainscricao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar notificação.
        /// </summary>
        public static string _DetailList_Botao_Consultanotificacao {
            get {
                return ResourceManager.GetString("_DetailList_Botao_Consultanotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar notificação.
        /// </summary>
        public static string _DetailList_Botao_Consultanotificacao_Tooltip {
            get {
                return ResourceManager.GetString("_DetailList_Botao_Consultanotificacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar histórico de situação da inscrição.
        /// </summary>
        public static string _DetailList_Botao_Historicosituacao {
            get {
                return ResourceManager.GetString("_DetailList_Botao_Historicosituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar observação sobre a inscrição.
        /// </summary>
        public static string _DetailList_Botao_Observacao {
            get {
                return ResourceManager.GetString("_DetailList_Botao_Observacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar documentação entregue.
        /// </summary>
        public static string _DetailList_Botao_Registrardocumentacaoentregue {
            get {
                return ResourceManager.GetString("_DetailList_Botao_Registrardocumentacaoentregue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        public static string _DetailList_Observacao_Modal_Titulo {
            get {
                return ResourceManager.GetString("_DetailList_Observacao_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta alteração de situação enviará um e-mail de notificação automático para o(s) candidato(s) selecionado(s), caso isso tenha sido configurado no processo. Confirma a alteração da situação?.
        /// </summary>
        public static string _OfertasDetailList_Mensagem_Confirmacao_Alteracao_Convocacao {
            get {
                return ResourceManager.GetString("_OfertasDetailList_Mensagem_Confirmacao_Alteracao_Convocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar situação.
        /// </summary>
        public static string _OfertasDetailList_Titulo_Confirmacao_Alteracao_Convocacao {
            get {
                return ResourceManager.GetString("_OfertasDetailList_Titulo_Confirmacao_Alteracao_Convocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar situação da convocação.
        /// </summary>
        public static string Botao_Convocacao {
            get {
                return ResourceManager.GetString("Botao_Convocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Botao_Fechar_Modal_Alterar_Situacao {
            get {
                return ResourceManager.GetString("Botao_Fechar_Modal_Alterar_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar histórico de situação da seleção.
        /// </summary>
        public static string Botao_Historicosituacao {
            get {
                return ResourceManager.GetString("Botao_Historicosituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer lançamento de resultado.
        /// </summary>
        public static string Botao_ModalArquivo_Tooltip {
            get {
                return ResourceManager.GetString("Botao_ModalArquivo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Oferta.
        /// </summary>
        public static string btn_alterar_oferta {
            get {
                return ResourceManager.GetString("btn_alterar_oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer lançamento de resultado.
        /// </summary>
        public static string btn_desfazer_lancamento {
            get {
                return ResourceManager.GetString("btn_desfazer_lancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançar resultado.
        /// </summary>
        public static string btn_lancar_resultado {
            get {
                return ResourceManager.GetString("btn_lancar_resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção indisponível. Este candidato não se encontra na etapa de seleção..
        /// </summary>
        public static string ButtonInstructions_nv013_botao_desabilitado {
            get {
                return ResourceManager.GetString("ButtonInstructions_nv013_botao_desabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de Inscrições por Candidato.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Oferta.
        /// </summary>
        public static string Label_AlterarOferta {
            get {
                return ResourceManager.GetString("Label_AlterarOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Situação .
        /// </summary>
        public static string Label_Convocacao {
            get {
                return ResourceManager.GetString("Label_Convocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja desfazer o lançamento do resultado do candidato {0}?.
        /// </summary>
        public static string Mensagem_Texto_DesfazerLancamento {
            get {
                return ResourceManager.GetString("Mensagem_Texto_DesfazerLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer lançamento.
        /// </summary>
        public static string Mensagem_Titulo_DesfazerLancamento {
            get {
                return ResourceManager.GetString("Mensagem_Titulo_DesfazerLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançar resultado.
        /// </summary>
        public static string tooltip_lancar_resultado {
            get {
                return ResourceManager.GetString("tooltip_lancar_resultado", resourceCulture);
            }
        }
    }
}
