//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.HierarquiaOferta.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.HierarquiaOferta.App_LocalResources.UIReso" +
                            "urce", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Período de Taxa em Lote.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Aba_Title_Exclusao {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Aba_Title_Exclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusão de Período de Taxa em Lote.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Aba_Title_Inclusao {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Aba_Title_Inclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Botao_Excluirtaxaemlote {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Botao_Excluirtaxaemlote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Botao_Excluirtaxaemlote_Tooltip {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Botao_Excluirtaxaemlote_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Botao_Incluir_Taxa {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Botao_Incluir_Taxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Botao_Incluir_Taxa_Tooltip {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Botao_Incluir_Taxa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas.
        /// </summary>
        public static string _AbasCadastroTaxaLote_GridExcluir_Grid_Titulo {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_GridExcluir_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas.
        /// </summary>
        public static string _AbasCadastroTaxaLote_GridIncluir_Grid_Titulo {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_GridIncluir_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão de todos os períodos de taxa das ofertas selecionadas?.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Mensagem_Exclusao_Taxa {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Mensagem_Exclusao_Taxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de exclusão de taxas.
        /// </summary>
        public static string _AbasCadastroTaxaLote_Titulo_Exclusao_Taxa {
            get {
                return ResourceManager.GetString("_AbasCadastroTaxaLote_Titulo_Exclusao_Taxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do item de hierarquia de oferta &quot;{0}“ e de todos os itens abaixo dele, inclusive suas ofertas?.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Item_Hierarquia_Oferta_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Item_Hierarquia_Oferta_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Item de Hierarquia de Oferta.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Item_Hierarquia_Oferta_Excluir_Titulo {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Item_Hierarquia_Oferta_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar item.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Link_Alterar_Item_Arvore_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Link_Alterar_Item_Arvore_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar oferta.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Link_Alterar_Oferta_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Link_Alterar_Oferta_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de oferta.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Link_Cadastro_Oferta_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Link_Cadastro_Oferta_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir item.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Link_Excluir_Item_Arvore_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Link_Excluir_Item_Arvore_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir oferta.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Link_Excluir_Oferta_Arvore_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Link_Excluir_Oferta_Arvore_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo ítem folha.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Link_Novo_Item_Folha_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Link_Novo_Item_Folha_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da oferta &quot;{0}“ e de todos os itens abaixo dela?.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Oferta_Hierarquia_Oferta_Excluir_Confirmacao {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Oferta_Hierarquia_Oferta_Excluir_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir oferta.
        /// </summary>
        public static string _ArvoreItemHierarquiaOferta_Oferta_Hierarquia_Oferta_Excluir_Titulo {
            get {
                return ResourceManager.GetString("_ArvoreItemHierarquiaOferta_Oferta_Hierarquia_Oferta_Excluir_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hierarquia de ofertas deste processo não pode ser alterada, porque ela é gerada a partir da integração com outro sistema..
        /// </summary>
        public static string _AssociarItemHierarquiaOferta_Label_PossuiIntegracao {
            get {
                return ResourceManager.GetString("_AssociarItemHierarquiaOferta_Label_PossuiIntegracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Códigos de Autorização.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Aba_Title_tabCodigosAutorizacao {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Aba_Title_tabCodigosAutorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Oferta.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosCancelamento {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosCancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da Oferta.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosOferta {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de Taxa.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosPeriodoTaxa {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosPeriodoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosResponsavel {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Aba_Title_tabDadosResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Complementar.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Aba_Title_tabDescricaoComplementar {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Aba_Title_tabDescricaoComplementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Códigos de autorização.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_CodigosAutorizacao_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_CodigosAutorizacao_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de item de hierarquia de oferta, a descrição da oferta, o número de vagas e o código de origem não podem ser alterados, pois eles dependem de informações cadastradas a partir da integração com outros sistemas..
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Label_PossuiIntegracao {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Label_PossuiIntegracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso as taxas associadas ao boleto do candidato possuam datas de vencimento distintas, o vencimento do boleto será gerado com a data maior..
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Mensagem_Taxa_Oferta {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Mensagem_Taxa_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas das permissões de inscrição fora do prazo.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Mensagem_TaxaPermissao_Oferta {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Mensagem_TaxaPermissao_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas da Oferta.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_TaxasOferta_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_TaxasOferta_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones.
        /// </summary>
        public static string _CadastrarOfertaHierarquiaOferta_Telefones_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_CadastrarOfertaHierarquiaOferta_Telefones_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Códigos de Autorização.
        /// </summary>
        public static string _CadastroOfertaHierarquiaOferta_fieldsetCodigosAutorizacao_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("_CadastroOfertaHierarquiaOferta_fieldsetCodigosAutorizacao_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova raiz.
        /// </summary>
        public static string _EditarHierarquiaOferta_Botao_Contextonovaitemhierarquia {
            get {
                return ResourceManager.GetString("_EditarHierarquiaOferta_Botao_Contextonovaitemhierarquia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova raiz.
        /// </summary>
        public static string _EditarHierarquiaOferta_Botao_Contextonovaitemhierarquia_Tooltip {
            get {
                return ResourceManager.GetString("_EditarHierarquiaOferta_Botao_Contextonovaitemhierarquia_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova oferta raiz.
        /// </summary>
        public static string _EditarHierarquiaOferta_Botao_Novo_Oferta_Raiz_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("_EditarHierarquiaOferta_Botao_Novo_Oferta_Raiz_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova oferta raiz.
        /// </summary>
        public static string _EditarHierarquiaOferta_Botao_Novo_Oferta_Raiz_Hierarquia_Oferta_Tooltip {
            get {
                return ResourceManager.GetString("_EditarHierarquiaOferta_Botao_Novo_Oferta_Raiz_Hierarquia_Oferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Taxa.
        /// </summary>
        public static string _IncluirTaxaEmLote_Botao_Insert_Taxas {
            get {
                return ResourceManager.GetString("_IncluirTaxaEmLote_Botao_Insert_Taxas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Taxa.
        /// </summary>
        public static string _IncluirTaxaEmLote_Botao_Insert_Taxas_Tooltip {
            get {
                return ResourceManager.GetString("_IncluirTaxaEmLote_Botao_Insert_Taxas_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso as taxas associadas ao boleto do candidato possuam datas de vencimento distintas, o vencimento do boleto será gerado com a data maior..
        /// </summary>
        public static string _IncluirTaxaEmLote_Mensagem_Taxa_Oferta {
            get {
                return ResourceManager.GetString("_IncluirTaxaEmLote_Mensagem_Taxa_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxas.
        /// </summary>
        public static string _IncluirTaxaEmLote_Taxas_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_IncluirTaxaEmLote_Taxas_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem taxas cadastradas para esta oferta..
        /// </summary>
        public static string _ListarOfertaPeriodo_Mensagem_Oferta_Sem_Taxas {
            get {
                return ResourceManager.GetString("_ListarOfertaPeriodo_Mensagem_Oferta_Sem_Taxas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Item da Hierarquia de Oferta.
        /// </summary>
        public static string Alterar_Item_Hierarquia_Oferta_Modal_Titulo {
            get {
                return ResourceManager.GetString("Alterar_Item_Hierarquia_Oferta_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Oferta.
        /// </summary>
        public static string Alterar_Oferta_Hierarquia_Oferta_Modal_Titulo {
            get {
                return ResourceManager.GetString("Alterar_Oferta_Hierarquia_Oferta_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Item da Hierarquia de Oferta.
        /// </summary>
        public static string Associar_Item_Hierarquia_Oferta_Modal_Titulo {
            get {
                return ResourceManager.GetString("Associar_Item_Hierarquia_Oferta_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividade.
        /// </summary>
        public static string Atividade_Label {
            get {
                return ResourceManager.GetString("Atividade_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo item raiz.
        /// </summary>
        public static string Botao_Novo_Item_Raiz_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("Botao_Novo_Item_Raiz_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo item raiz.
        /// </summary>
        public static string Botao_Novo_Item_Raiz_Hierarquia_Oferta_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Novo_Item_Raiz_Hierarquia_Oferta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Oferta.
        /// </summary>
        public static string Cadastrar_Oferta_Hierarquia_Oferta_Modal_Titulo {
            get {
                return ResourceManager.GetString("Cadastrar_Oferta_Hierarquia_Oferta_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusão de Período de Taxa em Lote.
        /// </summary>
        public static string CadastrarTaxaOferta_Modal_Incluir_Periodo_Taxa_Titulo {
            get {
                return ResourceManager.GetString("CadastrarTaxaOferta_Modal_Incluir_Periodo_Taxa_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleção de Ofertas para Manutenção de Taxa em Lote.
        /// </summary>
        public static string CadastrarTaxaOferta_Title {
            get {
                return ResourceManager.GetString("CadastrarTaxaOferta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Item da Hierarquia de Oferta.
        /// </summary>
        public static string Cadastro_Item_Hierarquia_Oferta_Modal_Titulo {
            get {
                return ResourceManager.GetString("Cadastro_Item_Hierarquia_Oferta_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços Eletrônicos.
        /// </summary>
        public static string EnderecosEletronicos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("EnderecosEletronicos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Hierarquia de Oferta.
        /// </summary>
        public static string HierarquiaOferta_Title {
            get {
                return ResourceManager.GetString("HierarquiaOferta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hierarquia de ofertas deste processo não pode ser alterada, porque ela é gerada a partir da integração com outro sistema..
        /// </summary>
        public static string Mensagem_Bloqueio_PossuiIntegracao {
            get {
                return ResourceManager.GetString("Mensagem_Bloqueio_PossuiIntegracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar período de taxa em lote.
        /// </summary>
        public static string TaxasOferta_Botao_Novo {
            get {
                return ResourceManager.GetString("TaxasOferta_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de Período de Taxa.
        /// </summary>
        public static string TaxasOferta_Title {
            get {
                return ResourceManager.GetString("TaxasOferta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar.
        /// </summary>
        public static string Texto_Informativo_Item_Arvore {
            get {
                return ResourceManager.GetString("Texto_Informativo_Item_Arvore", resourceCulture);
            }
        }
    }
}
