//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.AcompanhamentoCheckin.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.AcompanhamentoCheckin.App_LocalResources.M" +
                            "etadataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string CheckinLoteViewModel_DescricaoProcesso {
            get {
                return ResourceManager.GetString("CheckinLoteViewModel_DescricaoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in realizado?.
        /// </summary>
        public static string CheckinRealizado {
            get {
                return ResourceManager.GetString("CheckinRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da oferta.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data check-in.
        /// </summary>
        public static string DataHoraFormatado {
            get {
                return ResourceManager.GetString("DataHoraFormatado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ListarCheckinLoteViewModel_PossuiCheckin_FALSE {
            get {
                return ResourceManager.GetString("ListarCheckinLoteViewModel_PossuiCheckin_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ListarCheckinLoteViewModel_PossuiCheckin_TRUE {
            get {
                return ResourceManager.GetString("ListarCheckinLoteViewModel_PossuiCheckin_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in realizados.
        /// </summary>
        public static string NumeroChecinRealizado {
            get {
                return ResourceManager.GetString("NumeroChecinRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscritos.
        /// </summary>
        public static string NumeroInscrito {
            get {
                return ResourceManager.GetString("NumeroInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Vagas.
        /// </summary>
        public static string NumeroVagasOferta {
            get {
                return ResourceManager.GetString("NumeroVagasOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in?.
        /// </summary>
        public static string PossuiCheckin {
            get {
                return ResourceManager.GetString("PossuiCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in não realizado.
        /// </summary>
        public static string RestanteVagas {
            get {
                return ResourceManager.GetString("RestanteVagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item da hierarquia de oferta.
        /// </summary>
        public static string SeqItemHierarquiaOferta {
            get {
                return ResourceManager.GetString("SeqItemHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string SeqOferta {
            get {
                return ResourceManager.GetString("SeqOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in realizados.
        /// </summary>
        public static string TotalChekinsRealizados {
            get {
                return ResourceManager.GetString("TotalChekinsRealizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições.
        /// </summary>
        public static string TotalInscritos {
            get {
                return ResourceManager.GetString("TotalInscritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in não realizados.
        /// </summary>
        public static string TotalRestantes {
            get {
                return ResourceManager.GetString("TotalRestantes", resourceCulture);
            }
        }
    }
}
