//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Inscricao.Areas.INS.Views.NovaEntregaDocumentacao.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Inscricao.Areas.INS.Views.NovaEntregaDocumentacao.App_LocalResources.UIRe" +
                            "source", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Entrega da Documentação.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega da documentação realizada com sucesso..
        /// </summary>
        public static string Mensagem_Sucesso_Inclusao_Nova_Entrega_Documentacao {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Inclusao_Nova_Entrega_Documentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os arquivos anexados devem ter um tamanho máximo de 5 MB. Caso o arquivo ultrapasse esse tamanho, utilize ferramentas de compactação/compressão para reduzi-lo, antes de anexá-lo. Existem sites que permitem reduzir o tamanho de arquivos PDF de forma gratuita..
        /// </summary>
        public static string MSG_Tamanho_Maximo_Arquivo {
            get {
                return ResourceManager.GetString("MSG_Tamanho_Maximo_Arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação Documento.
        /// </summary>
        public static string SituacaoEntregaDocumento_Legenda_Titulo {
            get {
                return ResourceManager.GetString("SituacaoEntregaDocumento_Legenda_Titulo", resourceCulture);
            }
        }
    }
}
