//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.App_GlobalResources.MetadataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string CheckinLoteFiltroViewModel_CheckinRealizado_FALSE {
            get {
                return ResourceManager.GetString("CheckinLoteFiltroViewModel_CheckinRealizado_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string CheckinLoteFiltroViewModel_CheckinRealizado_TRUE {
            get {
                return ResourceManager.GetString("CheckinLoteFiltroViewModel_CheckinRealizado_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano de referência.
        /// </summary>
        public static string Class_AnoReferencia {
            get {
                return ResourceManager.GetString("Class_AnoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        public static string Class_ArquivoAnexado {
            get {
                return ResourceManager.GetString("Class_ArquivoAnexado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_Ativo_FALSE {
            get {
                return ResourceManager.GetString("Class_Ativo_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_Ativo_TRUE {
            get {
                return ResourceManager.GetString("Class_Ativo_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceladas.
        /// </summary>
        public static string Class_Canceladas {
            get {
                return ResourceManager.GetString("Class_Canceladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Class_CidadeNaturalidade {
            get {
                return ResourceManager.GetString("Class_CidadeNaturalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string Class_Classificacao {
            get {
                return ResourceManager.GetString("Class_Classificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Class_Cliente {
            get {
                return ResourceManager.GetString("Class_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string Class_Cnpj {
            get {
                return ResourceManager.GetString("Class_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Class_Codigo {
            get {
                return ResourceManager.GetString("Class_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. de área.
        /// </summary>
        public static string Class_CodigoArea {
            get {
                return ResourceManager.GetString("Class_CodigoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código EMS.
        /// </summary>
        public static string Class_CodigoEms {
            get {
                return ResourceManager.GetString("Class_CodigoEms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. de país.
        /// </summary>
        public static string Class_CodigoPais {
            get {
                return ResourceManager.GetString("Class_CodigoPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração.
        /// </summary>
        public static string Class_Configuracao {
            get {
                return ResourceManager.GetString("Class_Configuracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração da etapa.
        /// </summary>
        public static string Class_ConfiguracaoEtapa {
            get {
                return ResourceManager.GetString("Class_ConfiguracaoEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmadas.
        /// </summary>
        public static string Class_Confirmadas {
            get {
                return ResourceManager.GetString("Class_Confirmadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da nova senha​​.
        /// </summary>
        public static string Class_ConfirmarNovaSenha {
            get {
                return ResourceManager.GetString("Class_ConfirmarNovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondência.
        /// </summary>
        public static string Class_Correspondencia {
            get {
                return ResourceManager.GetString("Class_Correspondencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_Correspondencia_FALSE {
            get {
                return ResourceManager.GetString("Class_Correspondencia_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_Correspondencia_TRUE {
            get {
                return ResourceManager.GetString("Class_Correspondencia_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string Class_Cpf {
            get {
                return ResourceManager.GetString("Class_Cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF ou Passaporte.
        /// </summary>
        public static string Class_CpfouPassaporte {
            get {
                return ResourceManager.GetString("Class_CpfouPassaporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de cancelamento.
        /// </summary>
        public static string Class_DataCancelamento {
            get {
                return ResourceManager.GetString("Class_DataCancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de encerramento.
        /// </summary>
        public static string Class_DataEncerramento {
            get {
                return ResourceManager.GetString("Class_DataEncerramento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de entrega.
        /// </summary>
        public static string Class_DataEntrega {
            get {
                return ResourceManager.GetString("Class_DataEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Class_DataFim {
            get {
                return ResourceManager.GetString("Class_DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim antiga.
        /// </summary>
        public static string Class_DataFimAntiga {
            get {
                return ResourceManager.GetString("Class_DataFimAntiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim.
        /// </summary>
        public static string Class_DataFimTaxa {
            get {
                return ResourceManager.GetString("Class_DataFimTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de geração.
        /// </summary>
        public static string Class_DataGeracao {
            get {
                return ResourceManager.GetString("Class_DataGeracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data impressão boleto.
        /// </summary>
        public static string Class_DataImpressaoBoleto {
            get {
                return ResourceManager.GetString("Class_DataImpressaoBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Class_DataInicio {
            get {
                return ResourceManager.GetString("Class_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início.
        /// </summary>
        public static string Class_DataInicioTaxa {
            get {
                return ResourceManager.GetString("Class_DataInicioTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de inscrição.
        /// </summary>
        public static string Class_DataInscricao {
            get {
                return ResourceManager.GetString("Class_DataInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data limite.
        /// </summary>
        public static string Class_DataLimiteDocumentacao {
            get {
                return ResourceManager.GetString("Class_DataLimiteDocumentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        public static string Class_DataNascimento {
            get {
                return ResourceManager.GetString("Class_DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de pagamento.
        /// </summary>
        public static string Class_DataPagamento {
            get {
                return ResourceManager.GetString("Class_DataPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prazo de entrega.
        /// </summary>
        public static string Class_DataPrazoEntrega {
            get {
                return ResourceManager.GetString("Class_DataPrazoEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de vencimento.
        /// </summary>
        public static string Class_DataVencimento {
            get {
                return ResourceManager.GetString("Class_DataVencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data vencimento.
        /// </summary>
        public static string Class_DataVencimentto {
            get {
                return ResourceManager.GetString("Class_DataVencimentto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferidas.
        /// </summary>
        public static string Class_Deferidos {
            get {
                return ResourceManager.GetString("Class_Deferidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Class_DescPaisSelecionado {
            get {
                return ResourceManager.GetString("Class_DescPaisSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Class_Descricao {
            get {
                return ResourceManager.GetString("Class_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição complementar do processo.
        /// </summary>
        public static string Class_DescricaoComplementarProcesso {
            get {
                return ResourceManager.GetString("Class_DescricaoComplementarProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Class_DescricaoDocumentacao {
            get {
                return ResourceManager.GetString("Class_DescricaoDocumentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Class_DescricaoEtapaAtual {
            get {
                return ResourceManager.GetString("Class_DescricaoEtapaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do grupo.
        /// </summary>
        public static string Class_DescricaoGrupo {
            get {
                return ResourceManager.GetString("Class_DescricaoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de oferta.
        /// </summary>
        public static string Class_DescricaoGrupoOferta {
            get {
                return ResourceManager.GetString("Class_DescricaoGrupoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Class_DescricaoInformada {
            get {
                return ResourceManager.GetString("Class_DescricaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item de hierarquia de oferta superior.
        /// </summary>
        public static string Class_DescricaoItemHierarquiaOfertaSuperior {
            get {
                return ResourceManager.GetString("Class_DescricaoItemHierarquiaOfertaSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do label do código de autorização.
        /// </summary>
        public static string Class_DescricaoLabelCodigoAutorizacao {
            get {
                return ResourceManager.GetString("Class_DescricaoLabelCodigoAutorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do label do grupo de oferta.
        /// </summary>
        public static string Class_DescricaoLabelGrupoOferta {
            get {
                return ResourceManager.GetString("Class_DescricaoLabelGrupoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do label de oferta.
        /// </summary>
        public static string Class_DescricaoLabelOferta {
            get {
                return ResourceManager.GetString("Class_DescricaoLabelOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do link.
        /// </summary>
        public static string Class_DescricaoLink {
            get {
                return ResourceManager.GetString("Class_DescricaoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da naturalidade:.
        /// </summary>
        public static string Class_DescricaoNaturalidadeEstrangeira {
            get {
                return ResourceManager.GetString("Class_DescricaoNaturalidadeEstrangeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string Class_DescricaoOferta {
            get {
                return ResourceManager.GetString("Class_DescricaoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do processo.
        /// </summary>
        public static string Class_DescricaoProcesso {
            get {
                return ResourceManager.GetString("Class_DescricaoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação atual.
        /// </summary>
        public static string Class_DescricaoSituacaoAtual {
            get {
                return ResourceManager.GetString("Class_DescricaoSituacaoAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string Class_DescricaoTipoDocumento {
            get {
                return ResourceManager.GetString("Class_DescricaoTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo.
        /// </summary>
        public static string Class_DescricaoTipoProcesso {
            get {
                return ResourceManager.GetString("Class_DescricaoTipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação.
        /// </summary>
        public static string Class_Documentacao {
            get {
                return ResourceManager.GetString("Class_Documentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação Entregue?.
        /// </summary>
        public static string Class_DocumentacaoEntregue {
            get {
                return ResourceManager.GetString("Class_DocumentacaoEntregue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_DocumentacaoEntregue_FALSE {
            get {
                return ResourceManager.GetString("Class_DocumentacaoEntregue_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_DocumentacaoEntregue_TRUE {
            get {
                return ResourceManager.GetString("Class_DocumentacaoEntregue_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação entregue.
        /// </summary>
        public static string Class_DocumentacoesEntregues {
            get {
                return ResourceManager.GetString("Class_DocumentacoesEntregues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº do edital.
        /// </summary>
        public static string Class_Edital {
            get {
                return ResourceManager.GetString("Class_Edital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Class_Email {
            get {
                return ResourceManager.GetString("Class_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É oferta?.
        /// </summary>
        public static string Class_EOferta {
            get {
                return ResourceManager.GetString("Class_EOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_EOferta_FALSE {
            get {
                return ResourceManager.GetString("Class_EOferta_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_EOferta_TRUE {
            get {
                return ResourceManager.GetString("Class_EOferta_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil.
        /// </summary>
        public static string Class_EstadoCivil {
            get {
                return ResourceManager.GetString("Class_EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Class_EstadoNaturalidade {
            get {
                return ResourceManager.GetString("Class_EstadoNaturalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento taxa.
        /// </summary>
        public static string Class_EventoTaxa {
            get {
                return ResourceManager.GetString("Class_EventoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibe na relação geral?.
        /// </summary>
        public static string Class_ExibeRelacaoGeral {
            get {
                return ResourceManager.GetString("Class_ExibeRelacaoGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExibeRelacaoGeral_FALSE {
            get {
                return ResourceManager.GetString("Class_ExibeRelacaoGeral_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExibeRelacaoGeral_TRUE {
            get {
                return ResourceManager.GetString("Class_ExibeRelacaoGeral_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir dados no comprovante de inscrição?.
        /// </summary>
        public static string Class_ExibirDadosComprovanteInscricao {
            get {
                return ResourceManager.GetString("Class_ExibirDadosComprovanteInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExibirDadosComprovanteInscricao_FALSE {
            get {
                return ResourceManager.GetString("Class_ExibirDadosComprovanteInscricao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExibirDadosComprovanteInscricao_TRUE {
            get {
                return ResourceManager.GetString("Class_ExibirDadosComprovanteInscricao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir dados na página de confirmação de inscrição?.
        /// </summary>
        public static string Class_ExibirDadosPaginaConfirmacaoInscricao {
            get {
                return ResourceManager.GetString("Class_ExibirDadosPaginaConfirmacaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExibirDadosPaginaConfirmacaoInscricao_FALSE {
            get {
                return ResourceManager.GetString("Class_ExibirDadosPaginaConfirmacaoInscricao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExibirDadosPaginaConfirmacaoInscricao_TRUE {
            get {
                return ResourceManager.GetString("Class_ExibirDadosPaginaConfirmacaoInscricao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir na relação geral?.
        /// </summary>
        public static string Class_ExibirNaRelacaoGeral {
            get {
                return ResourceManager.GetString("Class_ExibirNaRelacaoGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExibirNaRelacaoGeral_FALSE {
            get {
                return ResourceManager.GetString("Class_ExibirNaRelacaoGeral_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExibirNaRelacaoGeral_TRUE {
            get {
                return ResourceManager.GetString("Class_ExibirNaRelacaoGeral_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExigeJustificativa_FALSE {
            get {
                return ResourceManager.GetString("Class_ExigeJustificativa_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExigeJustificativa_TRUE {
            get {
                return ResourceManager.GetString("Class_ExigeJustificativa_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exige pagamento de taxa?.
        /// </summary>
        public static string Class_ExigePagamentoTaxa {
            get {
                return ResourceManager.GetString("Class_ExigePagamentoTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExigePagamentoTaxa_FALSE {
            get {
                return ResourceManager.GetString("Class_ExigePagamentoTaxa_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExigePagamentoTaxa_TRUE {
            get {
                return ResourceManager.GetString("Class_ExigePagamentoTaxa_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe número máximo de inscrições?.
        /// </summary>
        public static string Class_ExisteNumeroMaximoInscricoes {
            get {
                return ResourceManager.GetString("Class_ExisteNumeroMaximoInscricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExisteNumeroMaximoInscricoes_FALSE {
            get {
                return ResourceManager.GetString("Class_ExisteNumeroMaximoInscricoes_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExisteNumeroMaximoInscricoes_TRUE {
            get {
                return ResourceManager.GetString("Class_ExisteNumeroMaximoInscricoes_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um nº máx. de inscrições por pessoa?.
        /// </summary>
        public static string Class_ExisteNumeroMaximoInscricoesPessoa {
            get {
                return ResourceManager.GetString("Class_ExisteNumeroMaximoInscricoesPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_ExisteNumeroMaximoInscricoesPessoa_FALSE {
            get {
                return ResourceManager.GetString("Class_ExisteNumeroMaximoInscricoesPessoa_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_ExisteNumeroMaximoInscricoesPessoa_TRUE {
            get {
                return ResourceManager.GetString("Class_ExisteNumeroMaximoInscricoesPessoa_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições concluídas.
        /// </summary>
        public static string Class_Finalizadas {
            get {
                return ResourceManager.GetString("Class_Finalizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma entrega.
        /// </summary>
        public static string Class_FormaEntrega {
            get {
                return ResourceManager.GetString("Class_FormaEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de entrega.
        /// </summary>
        public static string Class_FormaEntregaDocumento {
            get {
                return ResourceManager.GetString("Class_FormaEntregaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Class_Grupo {
            get {
                return ResourceManager.GetString("Class_Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de oferta.
        /// </summary>
        public static string Class_GrupoOferta {
            get {
                return ResourceManager.GetString("Class_GrupoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeferidas.
        /// </summary>
        public static string Class_Indeferidos {
            get {
                return ResourceManager.GetString("Class_Indeferidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições iniciadas.
        /// </summary>
        public static string Class_Iniciadas {
            get {
                return ResourceManager.GetString("Class_Iniciadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição somente com código de autorização?.
        /// </summary>
        public static string Class_InscricaoSomenteComCodigoAutorizacao {
            get {
                return ResourceManager.GetString("Class_InscricaoSomenteComCodigoAutorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_InscricaoSomenteComCodigoAutorizacao_FALSE {
            get {
                return ResourceManager.GetString("Class_InscricaoSomenteComCodigoAutorizacao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_InscricaoSomenteComCodigoAutorizacao_TRUE {
            get {
                return ResourceManager.GetString("Class_InscricaoSomenteComCodigoAutorizacao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição somente pelo cliente?.
        /// </summary>
        public static string Class_InscricaoSomentePeloCliente {
            get {
                return ResourceManager.GetString("Class_InscricaoSomentePeloCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_InscricaoSomentePeloCliente_FALSE {
            get {
                return ResourceManager.GetString("Class_InscricaoSomentePeloCliente_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_InscricaoSomentePeloCliente_TRUE {
            get {
                return ResourceManager.GetString("Class_InscricaoSomentePeloCliente_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite % desconto.
        /// </summary>
        public static string Class_LimitePercentualDesconto {
            get {
                return ResourceManager.GetString("Class_LimitePercentualDesconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo de documentos obrigatórios.
        /// </summary>
        public static string Class_MinimoDocumentosObrigatorios {
            get {
                return ResourceManager.GetString("Class_MinimoDocumentosObrigatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string Class_MotivoCancelamento {
            get {
                return ResourceManager.GetString("Class_MotivoCancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não confirmadas.
        /// </summary>
        public static string Class_NaoConfirmadas {
            get {
                return ResourceManager.GetString("Class_NaoConfirmadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Class_NomeCidade {
            get {
                return ResourceManager.GetString("Class_NomeCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Class_NomeCliente {
            get {
                return ResourceManager.GetString("Class_NomeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do contato.
        /// </summary>
        public static string Class_NomeContato {
            get {
                return ResourceManager.GetString("Class_NomeContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Class_NomeDisplay {
            get {
                return ResourceManager.GetString("Class_NomeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome fantasia.
        /// </summary>
        public static string Class_NomeFantasia {
            get {
                return ResourceManager.GetString("Class_NomeFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do inscrito.
        /// </summary>
        public static string Class_NomeInscrito {
            get {
                return ResourceManager.GetString("Class_NomeInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da mãe.
        /// </summary>
        public static string Class_NomeMae {
            get {
                return ResourceManager.GetString("Class_NomeMae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do pai.
        /// </summary>
        public static string Class_NomePai {
            get {
                return ResourceManager.GetString("Class_NomePai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome reduzido (Apelido).
        /// </summary>
        public static string Class_NomeReduzido {
            get {
                return ResourceManager.GetString("Class_NomeReduzido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do responsável.
        /// </summary>
        public static string Class_NomeResponsavel {
            get {
                return ResourceManager.GetString("Class_NomeResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome social.
        /// </summary>
        public static string Class_NomeSocial {
            get {
                return ResourceManager.GetString("Class_NomeSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade responsável.
        /// </summary>
        public static string Class_NomeUnidadeResponsavel {
            get {
                return ResourceManager.GetString("Class_NomeUnidadeResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string Class_Nota {
            get {
                return ResourceManager.GetString("Class_Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string Class_NotaGeral {
            get {
                return ResourceManager.GetString("Class_NotaGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        public static string Class_NovaSenha {
            get {
                return ResourceManager.GetString("Class_NovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Class_Numero {
            get {
                return ResourceManager.GetString("Class_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string Class_NumeroClassificacao {
            get {
                return ResourceManager.GetString("Class_NumeroClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de cópias requeridas.
        /// </summary>
        public static string Class_NumeroCopiasRequeridas {
            get {
                return ResourceManager.GetString("Class_NumeroCopiasRequeridas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Class_NumeroIdentidade {
            get {
                return ResourceManager.GetString("Class_NumeroIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número máximo de inscrições.
        /// </summary>
        public static string Class_NumeroMaximoInscricoes {
            get {
                return ResourceManager.GetString("Class_NumeroMaximoInscricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº máx. de inscrições por pessoa.
        /// </summary>
        public static string Class_NumeroMaximoInscricoesPessoa {
            get {
                return ResourceManager.GetString("Class_NumeroMaximoInscricoesPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº máx. de ofertas por inscrição.
        /// </summary>
        public static string Class_NumeroMaximoOfertasInscricao {
            get {
                return ResourceManager.GetString("Class_NumeroMaximoOfertasInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº máx. de opções por inscrição.
        /// </summary>
        public static string Class_NumeroMaximoOpcoesInscricao {
            get {
                return ResourceManager.GetString("Class_NumeroMaximoOpcoesInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção.
        /// </summary>
        public static string Class_NumeroOpcaoFormatado {
            get {
                return ResourceManager.GetString("Class_NumeroOpcaoFormatado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passaporte.
        /// </summary>
        public static string Class_NumeroPassaporte {
            get {
                return ResourceManager.GetString("Class_NumeroPassaporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string Class_NumeroRg {
            get {
                return ResourceManager.GetString("Class_NumeroRg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de vagas.
        /// </summary>
        public static string Class_NumeroVagas {
            get {
                return ResourceManager.GetString("Class_NumeroVagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatória?.
        /// </summary>
        public static string Class_Obrigatoria {
            get {
                return ResourceManager.GetString("Class_Obrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_Obrigatoria_FALSE {
            get {
                return ResourceManager.GetString("Class_Obrigatoria_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_Obrigatoria_TRUE {
            get {
                return ResourceManager.GetString("Class_Obrigatoria_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        public static string Class_Observacao {
            get {
                return ResourceManager.GetString("Class_Observacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta ativa?.
        /// </summary>
        public static string Class_OfertaAtiva {
            get {
                return ResourceManager.GetString("Class_OfertaAtiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_OfertaAtiva_FALSE {
            get {
                return ResourceManager.GetString("Class_OfertaAtiva_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_OfertaAtiva_TRUE {
            get {
                return ResourceManager.GetString("Class_OfertaAtiva_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas.
        /// </summary>
        public static string Class_Ofertas {
            get {
                return ResourceManager.GetString("Class_Ofertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta não selecionada.
        /// </summary>
        public static string Class_OfertasNaoSelecionadas {
            get {
                return ResourceManager.GetString("Class_OfertasNaoSelecionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção.
        /// </summary>
        public static string Class_Opcao {
            get {
                return ResourceManager.GetString("Class_Opcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edital.
        /// </summary>
        public static string Class_OpcaoLookupEditais {
            get {
                return ResourceManager.GetString("Class_OpcaoLookupEditais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string Class_OpcaoLookupOfertas {
            get {
                return ResourceManager.GetString("Class_OpcaoLookupOfertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgão Emissor.
        /// </summary>
        public static string Class_OrgaoEmissorIdentidade {
            get {
                return ResourceManager.GetString("Class_OrgaoEmissorIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgão emissor RG.
        /// </summary>
        public static string Class_OrgaoEmissorRg {
            get {
                return ResourceManager.GetString("Class_OrgaoEmissorRg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_Padrao_FALSE {
            get {
                return ResourceManager.GetString("Class_Padrao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_Padrao_TRUE {
            get {
                return ResourceManager.GetString("Class_Padrao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagas.
        /// </summary>
        public static string Class_Pagas {
            get {
                return ResourceManager.GetString("Class_Pagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string Class_Pagina {
            get {
                return ResourceManager.GetString("Class_Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País de origem.
        /// </summary>
        public static string Class_PaisNacionalidade {
            get {
                return ResourceManager.GetString("Class_PaisNacionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País de origem.
        /// </summary>
        public static string Class_PaisOrigem {
            get {
                return ResourceManager.GetString("Class_PaisOrigem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro CREI.
        /// </summary>
        public static string Class_ParametroCREI {
            get {
                return ResourceManager.GetString("Class_ParametroCREI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite agendamento de envio da notificação?.
        /// </summary>
        public static string Class_PermiteAgendamento {
            get {
                return ResourceManager.GetString("Class_PermiteAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite informar mais de uma opção?.
        /// </summary>
        public static string Class_PermiteInformarMaisDeUmaOpcao {
            get {
                return ResourceManager.GetString("Class_PermiteInformarMaisDeUmaOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_PermiteInformarMaisDeUmaOpcao_FALSE {
            get {
                return ResourceManager.GetString("Class_PermiteInformarMaisDeUmaOpcao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_PermiteInformarMaisDeUmaOpcao_TRUE {
            get {
                return ResourceManager.GetString("Class_PermiteInformarMaisDeUmaOpcao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite seleção na inscrição?.
        /// </summary>
        public static string Class_PermiteSelecaoInscricao {
            get {
                return ResourceManager.GetString("Class_PermiteSelecaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_PermiteSelecaoInscricao_FALSE {
            get {
                return ResourceManager.GetString("Class_PermiteSelecaoInscricao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_PermiteSelecaoInscricao_TRUE {
            get {
                return ResourceManager.GetString("Class_PermiteSelecaoInscricao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite upload?.
        /// </summary>
        public static string Class_PermiteUpload {
            get {
                return ResourceManager.GetString("Class_PermiteUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_PermiteUpload_FALSE {
            get {
                return ResourceManager.GetString("Class_PermiteUpload_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_PermiteUpload_TRUE {
            get {
                return ResourceManager.GetString("Class_PermiteUpload_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_PermiteVariosArquivos_FALSE {
            get {
                return ResourceManager.GetString("Class_PermiteVariosArquivos_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_PermiteVariosArquivos_TRUE {
            get {
                return ResourceManager.GetString("Class_PermiteVariosArquivos_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite vários códigos de autorização?.
        /// </summary>
        public static string Class_PermiteVariosCodigosAutorizacao {
            get {
                return ResourceManager.GetString("Class_PermiteVariosCodigosAutorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_PermiteVariosCodigosAutorizacao_FALSE {
            get {
                return ResourceManager.GetString("Class_PermiteVariosCodigosAutorizacao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_PermiteVariosCodigosAutorizacao_TRUE {
            get {
                return ResourceManager.GetString("Class_PermiteVariosCodigosAutorizacao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui deferimento?.
        /// </summary>
        public static string Class_PossuiDeferimento {
            get {
                return ResourceManager.GetString("Class_PossuiDeferimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_PossuiDeferimento_FALSE {
            get {
                return ResourceManager.GetString("Class_PossuiDeferimento_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_PossuiDeferimento_TRUE {
            get {
                return ResourceManager.GetString("Class_PossuiDeferimento_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_PossuiGrupo_FALSE {
            get {
                return ResourceManager.GetString("Class_PossuiGrupo_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_PossuiGrupo_TRUE {
            get {
                return ResourceManager.GetString("Class_PossuiGrupo_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade máxima.
        /// </summary>
        public static string Class_QuantidadeMaxima {
            get {
                return ResourceManager.GetString("Class_QuantidadeMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade mínima.
        /// </summary>
        public static string Class_QuantidadeMinima {
            get {
                return ResourceManager.GetString("Class_QuantidadeMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão social.
        /// </summary>
        public static string Class_RazaoSocial {
            get {
                return ResourceManager.GetString("Class_RazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string Class_Responsavel {
            get {
                return ResourceManager.GetString("Class_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seção.
        /// </summary>
        public static string Class_Secao {
            get {
                return ResourceManager.GetString("Class_Secao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem/Ano.
        /// </summary>
        public static string Class_SemestreAno {
            get {
                return ResourceManager.GetString("Class_SemestreAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre referência.
        /// </summary>
        public static string Class_SemestreReferencia {
            get {
                return ResourceManager.GetString("Class_SemestreReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Class_Seq {
            get {
                return ResourceManager.GetString("Class_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Class_SeqCliente {
            get {
                return ResourceManager.GetString("Class_SeqCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Class_SeqClienteSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqClienteSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de autorização.
        /// </summary>
        public static string Class_SeqCodigoAutorizacaoSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqCodigoAutorizacaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento.
        /// </summary>
        public static string Class_SeqElemento {
            get {
                return ResourceManager.GetString("Class_SeqElemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Class_SeqEtapaSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqEtapaSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário.
        /// </summary>
        public static string Class_SeqFormularioSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqFormularioSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de oferta.
        /// </summary>
        public static string Class_SeqGrupoOferta {
            get {
                return ResourceManager.GetString("Class_SeqGrupoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de oferta.
        /// </summary>
        public static string Class_SeqGrupoOfertaSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqGrupoOfertaSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Class_SeqIdiomaSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqIdiomaSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de inscrição.
        /// </summary>
        public static string Class_SeqInscricao {
            get {
                return ResourceManager.GetString("Class_SeqInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Class_SeqInscrito {
            get {
                return ResourceManager.GetString("Class_SeqInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens.
        /// </summary>
        public static string Class_SeqItenGrupoDocumentacaoRequeridaSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqItenGrupoDocumentacaoRequeridaSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Class_SeqPais {
            get {
                return ResourceManager.GetString("Class_SeqPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Class_SeqProcesso {
            get {
                return ResourceManager.GetString("Class_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Class_SeqProcessoOrigem {
            get {
                return ResourceManager.GetString("Class_SeqProcessoOrigem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Class_SeqSituacao {
            get {
                return ResourceManager.GetString("Class_SeqSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Class_SeqSituacaoDestino {
            get {
                return ResourceManager.GetString("Class_SeqSituacaoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Class_SeqSituacaoProcesso {
            get {
                return ResourceManager.GetString("Class_SeqSituacaoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Class_SeqSituacaoSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqSituacaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa.
        /// </summary>
        public static string Class_SeqTaxaSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTaxaSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template de processo.
        /// </summary>
        public static string Class_SeqTemplateProcessoSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTemplateProcessoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string Class_SeqTipoDocumentoSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTipoDocumentoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Formulário.
        /// </summary>
        public static string Class_SeqTipoFormularioSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTipoFormularioSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de hierarquia de oferta.
        /// </summary>
        public static string Class_SeqTipoHierarquiaOfertaSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTipoHierarquiaOfertaSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de item de hierarquia de oferta.
        /// </summary>
        public static string Class_SeqTipoItemHierarquiaOfertaSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTipoItemHierarquiaOfertaSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo.
        /// </summary>
        public static string Class_SeqTipoProcesso {
            get {
                return ResourceManager.GetString("Class_SeqTipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo.
        /// </summary>
        public static string Class_SeqTipoProcessoSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTipoProcessoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Class_SeqTipoProcessoSituacao {
            get {
                return ResourceManager.GetString("Class_SeqTipoProcessoSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Class_SeqTipoProcessoSituacaoDestino {
            get {
                return ResourceManager.GetString("Class_SeqTipoProcessoSituacaoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de template de processo.
        /// </summary>
        public static string Class_SeqTipoTemplateProcessoSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqTipoTemplateProcessoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Class_SeqTitulo {
            get {
                return ResourceManager.GetString("Class_SeqTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade responsável.
        /// </summary>
        public static string Class_SeqUnidadeResponsavel {
            get {
                return ResourceManager.GetString("Class_SeqUnidadeResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade responsável.
        /// </summary>
        public static string Class_SeqUnidadeResponsavelSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqUnidadeResponsavelSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão.
        /// </summary>
        public static string Class_SeqVersaoDocumentoSelecionado {
            get {
                return ResourceManager.GetString("Class_SeqVersaoDocumentoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visão.
        /// </summary>
        public static string Class_seqVisaoSelecionado {
            get {
                return ResourceManager.GetString("Class_seqVisaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Class_SiglaUf {
            get {
                return ResourceManager.GetString("Class_SiglaUf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Class_Situacao {
            get {
                return ResourceManager.GetString("Class_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validação.
        /// </summary>
        public static string Class_SituacaoEntregaDocumento {
            get {
                return ResourceManager.GetString("Class_SituacaoEntregaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação da Inscrição.
        /// </summary>
        public static string Class_SituacaoEtapa {
            get {
                return ResourceManager.GetString("Class_SituacaoEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação da inscrição.
        /// </summary>
        public static string Class_SituacaoInscricao {
            get {
                return ResourceManager.GetString("Class_SituacaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação da seleção.
        /// </summary>
        public static string Class_SituacaoOferta {
            get {
                return ResourceManager.GetString("Class_SituacaoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa de inscrição.
        /// </summary>
        public static string Class_TaxaInscricao {
            get {
                return ResourceManager.GetString("Class_TaxaInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa de inscrição.
        /// </summary>
        public static string Class_TaxaInscricaoPaga {
            get {
                return ResourceManager.GetString("Class_TaxaInscricaoPaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleto.
        /// </summary>
        public static string Class_TipoBoleto {
            get {
                return ResourceManager.GetString("Class_TipoBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string Class_TipoDocumento {
            get {
                return ResourceManager.GetString("Class_TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de endereço.
        /// </summary>
        public static string Class_TipoEndereco {
            get {
                return ResourceManager.GetString("Class_TipoEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de endereço eletrônico.
        /// </summary>
        public static string Class_TipoEnderecoEletronico {
            get {
                return ResourceManager.GetString("Class_TipoEnderecoEletronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Notificação.
        /// </summary>
        public static string Class_TipoNotificacao {
            get {
                return ResourceManager.GetString("Class_TipoNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo.
        /// </summary>
        public static string Class_TipoProcesso {
            get {
                return ResourceManager.GetString("Class_TipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de telefone.
        /// </summary>
        public static string Class_TipoTelefone {
            get {
                return ResourceManager.GetString("Class_TipoTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de unidade responsável.
        /// </summary>
        public static string Class_TipoUnidadeResponsavel {
            get {
                return ResourceManager.GetString("Class_TipoUnidadeResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtd. inscrições.
        /// </summary>
        public static string Class_Total {
            get {
                return ResourceManager.GetString("Class_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Class_UfIdentidade {
            get {
                return ResourceManager.GetString("Class_UfIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Class_UfNaturalidade {
            get {
                return ResourceManager.GetString("Class_UfNaturalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade.
        /// </summary>
        public static string Class_Unidade {
            get {
                return ResourceManager.GetString("Class_Unidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Responsável.
        /// </summary>
        public static string Class_UnidadeResponsavel {
            get {
                return ResourceManager.GetString("Class_UnidadeResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Class_ValorElemento {
            get {
                return ResourceManager.GetString("Class_ValorElemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão.
        /// </summary>
        public static string Class_Versao {
            get {
                return ResourceManager.GetString("Class_Versao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão do documento.
        /// </summary>
        public static string Class_VersaoDocumento {
            get {
                return ResourceManager.GetString("Class_VersaoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Configurar_Paginas_Etapa_Botao_Cancelar {
            get {
                return ResourceManager.GetString("Configurar_Paginas_Etapa_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Configurar_Paginas_Etapa_Botao_Cancelar_Tooltip {
            get {
                return ResourceManager.GetString("Configurar_Paginas_Etapa_Botao_Cancelar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição complementar do processo.
        /// </summary>
        public static string IdiomaProcessoViewModel_DescricaoComplementar {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_DescricaoComplementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string IdiomaProcessoViewModel_Idioma {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição label código de autorização.
        /// </summary>
        public static string IdiomaProcessoViewModel_LabelCodigoAutorizacao {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_LabelCodigoAutorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição label grupo de oferta.
        /// </summary>
        public static string IdiomaProcessoViewModel_LabelGrupoOferta {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_LabelGrupoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição label oferta.
        /// </summary>
        public static string IdiomaProcessoViewModel_LabelOferta {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_LabelOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padrão ?.
        /// </summary>
        public static string IdiomaProcessoViewModel_Padrao {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_Padrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string IdiomaProcessoViewModel_Padrao_FALSE {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_Padrao_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string IdiomaProcessoViewModel_Padrao_TRUE {
            get {
                return ResourceManager.GetString("IdiomaProcessoViewModel_Padrao_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir observação para inscrito?.
        /// </summary>
        public static string InscricaoDocumentoViewModel_ExibirObservacaoParaInscrito {
            get {
                return ResourceManager.GetString("InscricaoDocumentoViewModel_ExibirObservacaoParaInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string InscricaoDocumentoViewModel_ExibirObservacaoParaInscrito_FALSE {
            get {
                return ResourceManager.GetString("InscricaoDocumentoViewModel_ExibirObservacaoParaInscrito_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string InscricaoDocumentoViewModel_ExibirObservacaoParaInscrito_TRUE {
            get {
                return ResourceManager.GetString("InscricaoDocumentoViewModel_ExibirObservacaoParaInscrito_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string ItemGrupoOfertaViewModel_DescricaoCompleta {
            get {
                return ResourceManager.GetString("ItemGrupoOfertaViewModel_DescricaoCompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Atual.
        /// </summary>
        public static string ItemGrupoOfertaViewModel_NomeGrupoOferta {
            get {
                return ResourceManager.GetString("ItemGrupoOfertaViewModel_NomeGrupoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string LookupHierarquiaOfertaFiltroViewModel_DescricaoHierarquia {
            get {
                return ResourceManager.GetString("LookupHierarquiaOfertaFiltroViewModel_DescricaoHierarquia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string LookupHierarquiaOfertaFiltroViewModel_SeqItem {
            get {
                return ResourceManager.GetString("LookupHierarquiaOfertaFiltroViewModel_SeqItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de item.
        /// </summary>
        public static string LookupHierarquiaOfertaFiltroViewModel_SeqTipoItem {
            get {
                return ResourceManager.GetString("LookupHierarquiaOfertaFiltroViewModel_SeqTipoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string LookupHierarquiaOfertaViewModel_HierarquiaOferta {
            get {
                return ResourceManager.GetString("LookupHierarquiaOfertaViewModel_HierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de item.
        /// </summary>
        public static string LookupHierarquiaOfertaViewModel_TipoItemHierarquiaOferta {
            get {
                return ResourceManager.GetString("LookupHierarquiaOfertaViewModel_TipoItemHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Fim.
        /// </summary>
        public static string LookupOfertaPeriodoInscricaoViewModel_DataFim {
            get {
                return ResourceManager.GetString("LookupOfertaPeriodoInscricaoViewModel_DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início.
        /// </summary>
        public static string LookupOfertaPeriodoInscricaoViewModel_DataInicio {
            get {
                return ResourceManager.GetString("LookupOfertaPeriodoInscricaoViewModel_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exige entrega documentação?.
        /// </summary>
        public static string LookupOfertaPeriodoInscricaoViewModel_ExigeEntregaDocumentaaco {
            get {
                return ResourceManager.GetString("LookupOfertaPeriodoInscricaoViewModel_ExigeEntregaDocumentaaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string LookupOfertaPeriodoInscricaoViewModel_ExigeEntregaDocumentaaco_FALSE {
            get {
                return ResourceManager.GetString("LookupOfertaPeriodoInscricaoViewModel_ExigeEntregaDocumentaaco_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string LookupOfertaPeriodoInscricaoViewModel_ExigeEntregaDocumentaaco_TRUE {
            get {
                return ResourceManager.GetString("LookupOfertaPeriodoInscricaoViewModel_ExigeEntregaDocumentaaco_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições confirmadas.
        /// </summary>
        public static string LookupOfertaPeriodoInscricaoViewModel_InscricoesConfirmadas {
            get {
                return ResourceManager.GetString("LookupOfertaPeriodoInscricaoViewModel_InscricoesConfirmadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano referência.
        /// </summary>
        public static string LookupProcessoFiltroViewModel_AnoReferencia {
            get {
                return ResourceManager.GetString("LookupProcessoFiltroViewModel_AnoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre referência.
        /// </summary>
        public static string LookupProcessoFiltroViewModel_SemestreReferencia {
            get {
                return ResourceManager.GetString("LookupProcessoFiltroViewModel_SemestreReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo processo.
        /// </summary>
        public static string LookupProcessoFiltroViewModel_TipoProcesso {
            get {
                return ResourceManager.GetString("LookupProcessoFiltroViewModel_TipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Responsável.
        /// </summary>
        public static string LookupProcessoFiltroViewModel_UnidadeResponsavel {
            get {
                return ResourceManager.GetString("LookupProcessoFiltroViewModel_UnidadeResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano referência.
        /// </summary>
        public static string LookupProcessoViewModel_AnoReferencia {
            get {
                return ResourceManager.GetString("LookupProcessoViewModel_AnoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre referência .
        /// </summary>
        public static string LookupProcessoViewModel_SemestreReferencia {
            get {
                return ResourceManager.GetString("LookupProcessoViewModel_SemestreReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo processo.
        /// </summary>
        public static string LookupProcessoViewModel_TipoProcesso {
            get {
                return ResourceManager.GetString("LookupProcessoViewModel_TipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string ProcessoCabecalhoViewModel_Descricao {
            get {
                return ResourceManager.GetString("ProcessoCabecalhoViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Centro de Custo.
        /// </summary>
        public static string UnidadeFiltroLookupViewModel_CodigoCentroCusto {
            get {
                return ResourceManager.GetString("UnidadeFiltroLookupViewModel_CodigoCentroCusto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código EMS.
        /// </summary>
        public static string UnidadeListaLookupViewModel_CodigoEstabelecimentoEms {
            get {
                return ResourceManager.GetString("UnidadeListaLookupViewModel_CodigoEstabelecimentoEms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome centro de custo.
        /// </summary>
        public static string UnidadeListaLookupViewModel_NomeCentroCusto {
            get {
                return ResourceManager.GetString("UnidadeListaLookupViewModel_NomeCentroCusto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigência.
        /// </summary>
        public static string UnidadeListaLookupViewModel_Vigencia {
            get {
                return ResourceManager.GetString("UnidadeListaLookupViewModel_Vigencia", resourceCulture);
            }
        }
    }
}
