//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.GrupoDocumentoRequerido.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.GrupoDocumentoRequerido.App_LocalResources" +
                            ".UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo item.
        /// </summary>
        public static string _EditarGrupoDocumentosRequeridos_Botao_Insert_Itens_Tooltip {
            get {
                return ResourceManager.GetString("_EditarGrupoDocumentosRequeridos_Botao_Insert_Itens_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens do Grupo.
        /// </summary>
        public static string _EditarGrupoDocumentosRequeridos_Itens_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_EditarGrupoDocumentosRequeridos_Itens_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas documentos requeridos configurados como não obrigatórios e com upload não obrigatório podem ser associados a um grupo de documentos..
        /// </summary>
        public static string _EditarGrupoDocumentosRequeridos_Mensagem_Documentos_Requeridos_Grupo {
            get {
                return ResourceManager.GetString("_EditarGrupoDocumentosRequeridos_Mensagem_Documentos_Requeridos_Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string _ListarGrupoDocumentosRequeridos_Botao_Alterar_Grupo_Documentacao_Requerida_Tooltip {
            get {
                return ResourceManager.GetString("_ListarGrupoDocumentosRequeridos_Botao_Alterar_Grupo_Documentacao_Requerida_Toolt" +
                        "ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do Grupo de Documentação Requerida &quot;{0}&quot;?.
        /// </summary>
        public static string _ListarGrupoDocumentosRequeridos_Exclusao_Grupo_Documentacao_Requerida_Confirmacao {
            get {
                return ResourceManager.GetString("_ListarGrupoDocumentosRequeridos_Exclusao_Grupo_Documentacao_Requerida_Confirmaca" +
                        "o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir grupo de documentação requerida.
        /// </summary>
        public static string _ListarGrupoDocumentosRequeridos_Exclusao_Grupo_Documentacao_Requerida_Title {
            get {
                return ResourceManager.GetString("_ListarGrupoDocumentosRequeridos_Exclusao_Grupo_Documentacao_Requerida_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do grupo:.
        /// </summary>
        public static string _ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_DescricaoGrupo {
            get {
                return ResourceManager.GetString("_ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_DescricaoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens do grupo:.
        /// </summary>
        public static string _ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_ItensGrupo {
            get {
                return ResourceManager.GetString("_ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_ItensGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo de documentos obrigatórios:.
        /// </summary>
        public static string _ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_MinimoDocumentosObrigatorios {
            get {
                return ResourceManager.GetString("_ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_MinimoDocumentosObr" +
                        "igatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload obrigatório?.
        /// </summary>
        public static string _ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_UploadObrigatorio {
            get {
                return ResourceManager.GetString("_ListarGrupoDocumentosRequeridos_Grupo_Documentacao_Requerida_UploadObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Grupo de Documentação Requerida.
        /// </summary>
        public static string Alterar_Grupo_Documentacao_Requerida {
            get {
                return ResourceManager.GetString("Alterar_Grupo_Documentacao_Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições com documento cadastrado para este grupo de documentos. Deseja continuar?.
        /// </summary>
        public static string Assert_AlterarItemGrupoDocumento {
            get {
                return ResourceManager.GetString("Assert_AlterarItemGrupoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições com documento cadastrado para este grupo de documentos. A alteração da quantidade mínima fará com que os documentos anexados destas inscrições fiquem inconsistentes com relação ao novo valor informado. Deseja continuar?.
        /// </summary>
        public static string Assert_NumeroMinimoObrigatorio {
            get {
                return ResourceManager.GetString("Assert_NumeroMinimoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem inscrições que já fizeram o upload de documentos e não poderão anexar um arquivo para este novo documento. Deseja continuar?.
        /// </summary>
        public static string Assert_UploadObrigatorio {
            get {
                return ResourceManager.GetString("Assert_UploadObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo item.
        /// </summary>
        public static string Botao_Insert_Itens_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Insert_Itens_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Grupo de Documentação Requerida.
        /// </summary>
        public static string Incluir_Grupo_Documentacao_Requerida {
            get {
                return ResourceManager.GetString("Incluir_Grupo_Documentacao_Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo grupo.
        /// </summary>
        public static string Index_Botao_Incluir_Grupo_Documentacao_Requerida {
            get {
                return ResourceManager.GetString("Index_Botao_Incluir_Grupo_Documentacao_Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo grupo.
        /// </summary>
        public static string Index_Botao_Incluir_Grupo_Documentacao_Requerida_Tooltip {
            get {
                return ResourceManager.GetString("Index_Botao_Incluir_Grupo_Documentacao_Requerida_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Grupo de Documentação Requerida.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar grupo de documentação requerida.
        /// </summary>
        public static string Modal_Alter_Grupo_Titulo {
            get {
                return ResourceManager.GetString("Modal_Alter_Grupo_Titulo", resourceCulture);
            }
        }
    }
}
