//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.RES.Views.UnidadeResponsavel.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.RES.Views.UnidadeResponsavel.App_LocalResources.Meta" +
                            "dataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema/Origem GAD.
        /// </summary>
        public static string TokenSistemaOrigemGad {
            get {
                return ResourceManager.GetString("TokenSistemaOrigemGad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Responsável.
        /// </summary>
        public static string UnidadeResponsavelCabecalhoViewModel_UnidadeResponsavel {
            get {
                return ResourceManager.GetString("UnidadeResponsavelCabecalhoViewModel_UnidadeResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Custo.
        /// </summary>
        public static string UnidadeResponsavelCentroCustoViewModel_CentroCusto {
            get {
                return ResourceManager.GetString("UnidadeResponsavelCentroCustoViewModel_CentroCusto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID inválido.
        /// </summary>
        public static string UnidadeResponsavelFiltroViewModel_Seq_MaxValue {
            get {
                return ResourceManager.GetString("UnidadeResponsavelFiltroViewModel_Seq_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade.
        /// </summary>
        public static string UnidadeResponsavelViewModel_CodigoUnidade {
            get {
                return ResourceManager.GetString("UnidadeResponsavelViewModel_CodigoUnidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string UnidadeResponsavelViewModel_Enderecos {
            get {
                return ResourceManager.GetString("UnidadeResponsavelViewModel_Enderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade responsável notificação.
        /// </summary>
        public static string UnidadeResponsavelViewModel_SeqUnidadeResponsavelNotificacao {
            get {
                return ResourceManager.GetString("UnidadeResponsavelViewModel_SeqUnidadeResponsavelNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade responsável SGF.
        /// </summary>
        public static string UnidadeResponsavelViewModel_SeqUnidadeResponsavelSgf {
            get {
                return ResourceManager.GetString("UnidadeResponsavelViewModel_SeqUnidadeResponsavelSgf", resourceCulture);
            }
        }
    }
}
