//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.RES.Views.UnidadeResponsavel.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.RES.Views.UnidadeResponsavel.App_LocalResources.UIRe" +
                            "source", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo centro de custo.
        /// </summary>
        public static string _EditarUnidadeResponsavel_Botao_Insert_CentrosCusto_Tooltip {
            get {
                return ResourceManager.GetString("_EditarUnidadeResponsavel_Botao_Insert_CentrosCusto_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo endereço eletrônico.
        /// </summary>
        public static string _EditarUnidadeResponsavel_Botao_Insert_EnderecosEletronicos_Tooltip {
            get {
                return ResourceManager.GetString("_EditarUnidadeResponsavel_Botao_Insert_EnderecosEletronicos_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo telefone.
        /// </summary>
        public static string _EditarUnidadeResponsavel_Botao_Insert_Telefones_Tooltip {
            get {
                return ResourceManager.GetString("_EditarUnidadeResponsavel_Botao_Insert_Telefones_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Custo.
        /// </summary>
        public static string _EditarUnidadeResponsavel_CentrosCusto_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_EditarUnidadeResponsavel_CentrosCusto_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços Eletrônicos.
        /// </summary>
        public static string _EditarUnidadeResponsavel_EnderecosEletronicos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("_EditarUnidadeResponsavel_EnderecosEletronicos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string _EditarUnidadeResponsavel_fieldsetCadastroContato_Fieldset_Legenda {
            get {
                return ResourceManager.GetString("_EditarUnidadeResponsavel_fieldsetCadastroContato_Fieldset_Legenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração da Unidade Responsável.
        /// </summary>
        public static string _ListarUnidadeResponsavel_Botao_Configurar {
            get {
                return ResourceManager.GetString("_ListarUnidadeResponsavel_Botao_Configurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração da Unidade Responsável.
        /// </summary>
        public static string _ListarUnidadeResponsavel_Botao_Configurar_Tooltip {
            get {
                return ResourceManager.GetString("_ListarUnidadeResponsavel_Botao_Configurar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades Responsáveis.
        /// </summary>
        public static string _ListarUnidadeResponsavel_gridUnidadeResponsavel_Grid_Titulo {
            get {
                return ResourceManager.GetString("_ListarUnidadeResponsavel_gridUnidadeResponsavel_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinatura Digital.
        /// </summary>
        public static string AssinaturaDigital_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("AssinaturaDigital_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de tipo de formulário.
        /// </summary>
        public static string Configurar_Modal_TipoFormulario {
            get {
                return ResourceManager.GetString("Configurar_Modal_TipoFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de Tipo de Processo e Tipos de Hierarquia de Oferta.
        /// </summary>
        public static string Configurar_Modal_TipoProcesso {
            get {
                return ResourceManager.GetString("Configurar_Modal_TipoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação de tipo de processo e tipo de hierarquia de oferta.
        /// </summary>
        public static string Configurar_Modal_TipoProcesso_TipoHierarquiaOferta {
            get {
                return ResourceManager.GetString("Configurar_Modal_TipoProcesso_TipoHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração da Unidade Responsável.
        /// </summary>
        public static string Configurar_Title {
            get {
                return ResourceManager.GetString("Configurar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Unidade Responsável.
        /// </summary>
        public static string Editar_Title {
            get {
                return ResourceManager.GetString("Editar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Enderecos_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Enderecos_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da Unidade Responsável &quot;{0}&quot;?.
        /// </summary>
        public static string Exclusao_Unidade_Responsavel_Confirmacao {
            get {
                return ResourceManager.GetString("Exclusao_Unidade_Responsavel_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Unidade Responsável.
        /// </summary>
        public static string Exclusao_Unidade_Responsavel_Title {
            get {
                return ResourceManager.GetString("Exclusao_Unidade_Responsavel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string gridConfiguracaoTipoFormulario_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridConfiguracaoTipoFormulario_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string gridConfiguracaoTipoProcesso_Grid_Titulo {
            get {
                return ResourceManager.GetString("gridConfiguracaoTipoProcesso_Grid_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Unidade Responsável.
        /// </summary>
        public static string Incluir_Title {
            get {
                return ResourceManager.GetString("Incluir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova unidade responsável.
        /// </summary>
        public static string Index_Botao_Novo {
            get {
                return ResourceManager.GetString("Index_Botao_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova unidade responsável.
        /// </summary>
        public static string Index_Botao_Novo_Tooltip {
            get {
                return ResourceManager.GetString("Index_Botao_Novo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Unidade Responsável.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração realizada com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Alteracao_Associacao_Tipo_Processo_Tipo_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Alteracao_Associacao_Tipo_Processo_Tipo_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Formulário associado com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Associacao_Tipo_Formulario {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Associacao_Tipo_Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Processo e Tipo de Hierarquia de Oferta associados com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Associacao_Tipo_Processo_Tipo_Hierarquia_Oferta {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Associacao_Tipo_Processo_Tipo_Hierarquia_Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação ao tipo de formulário excluída com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Exclusao_Associacao_Tipo_Formulario {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Exclusao_Associacao_Tipo_Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associação ao tipo de processo e tipo de hierarquia de oferta excluída com sucesso.
        /// </summary>
        public static string Mensagem_Sucesso_Exclusao_Associacao_Tipo_Processo {
            get {
                return ResourceManager.GetString("Mensagem_Sucesso_Exclusao_Associacao_Tipo_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones.
        /// </summary>
        public static string Telefones_Detalhe_Titulo {
            get {
                return ResourceManager.GetString("Telefones_Detalhe_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Formulário.
        /// </summary>
        public static string Titulo_Gadget_Tipo_Formulario {
            get {
                return ResourceManager.GetString("Titulo_Gadget_Tipo_Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Processo.
        /// </summary>
        public static string Titulo_Gadget_Tipo_Processo {
            get {
                return ResourceManager.GetString("Titulo_Gadget_Tipo_Processo", resourceCulture);
            }
        }
    }
}
