//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.SEL.Views.AnaliseSelecao.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.SEL.Views.AnaliseSelecao.App_LocalResources.Metadata" +
                            "Resource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string AnaliseSelecaoLoteFiltroViewModel_Descricao {
            get {
                return ResourceManager.GetString("AnaliseSelecaoLoteFiltroViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item da Hierarquia de Oferta.
        /// </summary>
        public static string AnaliseSelecaoLoteFiltroViewModel_SeqItemHierarquiaOferta {
            get {
                return ResourceManager.GetString("AnaliseSelecaoLoteFiltroViewModel_SeqItemHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string AnaliseSelecaoLoteFiltroViewModel_SeqMotivo {
            get {
                return ResourceManager.GetString("AnaliseSelecaoLoteFiltroViewModel_SeqMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string AnaliseSelecaoLoteFiltroViewModel_SeqOferta {
            get {
                return ResourceManager.GetString("AnaliseSelecaoLoteFiltroViewModel_SeqOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AnaliseSelecaoLoteFiltroViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("AnaliseSelecaoLoteFiltroViewModel_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Inscrição.
        /// </summary>
        public static string ConvocacaoItemViewModel_SeqInscricaoDisplay {
            get {
                return ResourceManager.GetString("ConvocacaoItemViewModel_SeqInscricaoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string ConvocacaoViewModel_SeqMotivoSGF {
            get {
                return ResourceManager.GetString("ConvocacaoViewModel_SeqMotivoSGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação atual.
        /// </summary>
        public static string ConvocacaoViewModel_SituacaoAtual {
            get {
                return ResourceManager.GetString("ConvocacaoViewModel_SituacaoAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string HistoricoSituacaoListaViewModel_Descricao {
            get {
                return ResourceManager.GetString("HistoricoSituacaoListaViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string HistoricoSituacaoListaViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("HistoricoSituacaoListaViewModel_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string HistoricoSituacaoViewModel_Descricao {
            get {
                return ResourceManager.GetString("HistoricoSituacaoViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string HistoricoSituacaoViewModel_SeqMotivo {
            get {
                return ResourceManager.GetString("HistoricoSituacaoViewModel_SeqMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string HistoricoSituacaoViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("HistoricoSituacaoViewModel_SeqProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        public static string LancamentoResultadoItemViewModel_DescricaoResultadoSelecao {
            get {
                return ResourceManager.GetString("LancamentoResultadoItemViewModel_DescricaoResultadoSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ª Nota / % Bolsa.
        /// </summary>
        public static string LancamentoResultadoItemViewModel_Nota {
            get {
                return ResourceManager.GetString("LancamentoResultadoItemViewModel_Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de opções para as quais deseja ser convocado(a), respeitando a ordem de prioridade.
        /// </summary>
        public static string LancamentoResultadoItemViewModel_NumeroOpcoesDesejadas {
            get {
                return ResourceManager.GetString("LancamentoResultadoItemViewModel_NumeroOpcoesDesejadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parecer responsável.
        /// </summary>
        public static string LancamentoResultadoItemViewModel_ParecerResponsavel {
            get {
                return ResourceManager.GetString("LancamentoResultadoItemViewModel_ParecerResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ª Nota / % Financiamento.
        /// </summary>
        public static string LancamentoResultadoItemViewModel_SegundaNota {
            get {
                return ResourceManager.GetString("LancamentoResultadoItemViewModel_SegundaNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string LancamentoResultadoItemViewModel_SeqMotivo {
            get {
                return ResourceManager.GetString("LancamentoResultadoItemViewModel_SeqMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        public static string LancamentoResultadoItemViewModel_SeqResultadoSelecao {
            get {
                return ResourceManager.GetString("LancamentoResultadoItemViewModel_SeqResultadoSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string LancamentoResultadoViewModel_Descricao {
            get {
                return ResourceManager.GetString("LancamentoResultadoViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string LancamentoResultadoViewModel_SeqProcesso {
            get {
                return ResourceManager.GetString("LancamentoResultadoViewModel_SeqProcesso", resourceCulture);
            }
        }
    }
}
