//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Inscricao.Views.Home.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Inscricao.Views.Home.App_LocalResources.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscreva-se.
        /// </summary>
        internal static string _ListarEtapaInscricao_Botao_Inscrever {
            get {
                return ResourceManager.GetString("_ListarEtapaInscricao_Botao_Inscrever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscreva-se.
        /// </summary>
        internal static string _ListarEtapaInscricao_Botao_Inscrever_Tooltip {
            get {
                return ResourceManager.GetString("_ListarEtapaInscricao_Botao_Inscrever_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quero me inscrever.
        /// </summary>
        internal static string _ListarEtapaInscricaoProcesso_Botao_Inscrever {
            get {
                return ResourceManager.GetString("_ListarEtapaInscricaoProcesso_Botao_Inscrever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quero me inscrever.
        /// </summary>
        internal static string _ListarEtapaInscricaoProcesso_Botao_Inscrever_Tooltip {
            get {
                return ResourceManager.GetString("_ListarEtapaInscricaoProcesso_Botao_Inscrever_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar Inscrição.
        /// </summary>
        internal static string _ListarInscricoes_Botao_Continuarinscricao {
            get {
                return ResourceManager.GetString("_ListarInscricoes_Botao_Continuarinscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar Inscrição.
        /// </summary>
        internal static string _ListarInscricoes_Botao_Continuarinscricao_Tooltip {
            get {
                return ResourceManager.GetString("_ListarInscricoes_Botao_Continuarinscricao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessar.
        /// </summary>
        internal static string _ListarInscricoes_Botao_Homeprocesso {
            get {
                return ResourceManager.GetString("_ListarInscricoes_Botao_Homeprocesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessar.
        /// </summary>
        internal static string _ListarInscricoes_Botao_Homeprocesso_Tooltip {
            get {
                return ResourceManager.GetString("_ListarInscricoes_Botao_Homeprocesso_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregar documentação.
        /// </summary>
        internal static string _ListarInscricoes_Botao_Novaentregadocumentacao {
            get {
                return ResourceManager.GetString("_ListarInscricoes_Botao_Novaentregadocumentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregar documentação.
        /// </summary>
        internal static string _ListarInscricoes_Botao_Novaentregadocumentacao_Tooltip {
            get {
                return ResourceManager.GetString("_ListarInscricoes_Botao_Novaentregadocumentacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar Inscrição.
        /// </summary>
        internal static string _ListarInscricoesProcesso_Botao_Continuarinscricao {
            get {
                return ResourceManager.GetString("_ListarInscricoesProcesso_Botao_Continuarinscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar Inscrição.
        /// </summary>
        internal static string _ListarInscricoesProcesso_Botao_Continuarinscricao_Tooltip {
            get {
                return ResourceManager.GetString("_ListarInscricoesProcesso_Botao_Continuarinscricao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação Pendente.
        /// </summary>
        internal static string _ListarInscricoesProcesso_Botao_Novaentregadocumentacao {
            get {
                return ResourceManager.GetString("_ListarInscricoesProcesso_Botao_Novaentregadocumentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação Pendente.
        /// </summary>
        internal static string _ListarInscricoesProcesso_Botao_Novaentregadocumentacao_Tooltip {
            get {
                return ResourceManager.GetString("_ListarInscricoesProcesso_Botao_Novaentregadocumentacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar agendamento.
        /// </summary>
        internal static string Botao_Continuarinscricaoagendamento {
            get {
                return ResourceManager.GetString("Botao_Continuarinscricaoagendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar entrega.
        /// </summary>
        internal static string Botao_Continuarinscricaoentrega_De_Documentacao {
            get {
                return ResourceManager.GetString("Botao_Continuarinscricaoentrega_De_Documentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar inscrição.
        /// </summary>
        internal static string Botao_Continuarinscricaoinscricao {
            get {
                return ResourceManager.GetString("Botao_Continuarinscricaoinscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Documentação.
        /// </summary>
        internal static string Botao_EmitirDocumentacao {
            get {
                return ResourceManager.GetString("Botao_EmitirDocumentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Documentação.
        /// </summary>
        internal static string Botao_Emitirdocumentacao_Tooltip {
            get {
                return ResourceManager.GetString("Botao_Emitirdocumentacao_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliar.
        /// </summary>
        internal static string Botao_FormularioImpacato {
            get {
                return ResourceManager.GetString("Botao_FormularioImpacato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Botao_Home {
            get {
                return ResourceManager.GetString("Botao_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingressos.
        /// </summary>
        internal static string Botao_Ingressos {
            get {
                return ResourceManager.GetString("Botao_Ingressos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Botao_Inicio {
            get {
                return ResourceManager.GetString("Botao_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizar agendamento.
        /// </summary>
        internal static string Botao_Inscreveragendamento {
            get {
                return ResourceManager.GetString("Botao_Inscreveragendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregar Documentação.
        /// </summary>
        internal static string Botao_Inscreverentrega_De_Documentacao {
            get {
                return ResourceManager.GetString("Botao_Inscreverentrega_De_Documentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quero me inscrever.
        /// </summary>
        internal static string Botao_Inscreverinscricao {
            get {
                return ResourceManager.GetString("Botao_Inscreverinscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprovante.
        /// </summary>
        internal static string Botao_Linkcomprovante {
            get {
                return ResourceManager.GetString("Botao_Linkcomprovante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus dados.
        /// </summary>
        internal static string Botao_Meusdados {
            get {
                return ResourceManager.GetString("Botao_Meusdados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        internal static string Botao_Pesquisar {
            get {
                return ResourceManager.GetString("Botao_Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todas.
        /// </summary>
        internal static string Botao_Verinscricoes {
            get {
                return ResourceManager.GetString("Botao_Verinscricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todos.
        /// </summary>
        internal static string Botao_Verprocessos {
            get {
                return ResourceManager.GetString("Botao_Verprocessos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conte como foi sua experiência.
        /// </summary>
        internal static string Chamada_Formulario_Impacto {
            get {
                return ResourceManager.GetString("Chamada_Formulario_Impacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua opinião é crucial para aprimorarmos futuros eventos. Por favor, reserve alguns minutos para compartilhar suas impressões. Agradecemos antecipadamente por sua contribuição valiosa, que nos ajudará a oferecer experiências ainda melhores..
        /// </summary>
        internal static string Chamada_Formulario_Impacto_Complemento {
            get {
                return ResourceManager.GetString("Chamada_Formulario_Impacto_Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponível até.
        /// </summary>
        internal static string Chamada_Formulario_Impacto_Disponivel {
            get {
                return ResourceManager.GetString("Chamada_Formulario_Impacto_Disponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de Avaliação.
        /// </summary>
        internal static string FormualarioImpacto_Modal_Titulo {
            get {
                return ResourceManager.GetString("FormualarioImpacto_Modal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string Label_Periodo {
            get {
                return ResourceManager.GetString("Label_Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento de taxa em aberto..
        /// </summary>
        internal static string Mensagem_Informativa_Checkin_Desabilitada {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Checkin_Desabilitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui para visualizar os QR Codes de acesso..
        /// </summary>
        internal static string Mensagem_Informativa_Checkin_Habilitada {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Checkin_Habilitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você possui documentos pendentes. Clique em &quot;Documentação Pendente&quot; para anexá-los. Você tem ate o dia {0} para realizar a nova entrega da documentação..
        /// </summary>
        internal static string Mensagem_Informativa_Entrega_Documentacao {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Entrega_Documentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento indisponível..
        /// </summary>
        internal static string Mensagem_Informativa_Inscricao_Indisponivel_AGENDAMENTO {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Inscricao_Indisponivel_AGENDAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega de documentação indisponível..
        /// </summary>
        internal static string Mensagem_Informativa_Inscricao_Indisponivel_ENTREGA_DE_DOCUMENTACAO {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Inscricao_Indisponivel_ENTREGA_DE_DOCUMENTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição indisponível..
        /// </summary>
        internal static string Mensagem_Informativa_Inscricao_Indisponivel_INSCRICAO {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Inscricao_Indisponivel_INSCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O agendamento encontra-se temporariamente indisponível..
        /// </summary>
        internal static string Mensagem_Informativa_Inscricoes_Em_Manutencao_AGENDAMENTO {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Inscricoes_Em_Manutencao_AGENDAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A entrega de documentação encontra-se temporariamente indisponível..
        /// </summary>
        internal static string Mensagem_Informativa_Inscricoes_Em_Manutencao_ENTREGA_DE_DOCUMENTACAO {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Inscricoes_Em_Manutencao_ENTREGA_DE_DOCUMENTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A inscrição encontra-se temporariamente indisponível..
        /// </summary>
        internal static string Mensagem_Informativa_Inscricoes_Em_Manutencao_INSCRICAO {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Inscricoes_Em_Manutencao_INSCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este processo encontra-se {0}..
        /// </summary>
        internal static string Mensagem_Informativa_Inscricoes_Nao_Liberada {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Inscricoes_Nao_Liberada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não selecionado(a)..
        /// </summary>
        internal static string Mensagem_Informativa_Oferta_Nao_Selecionada {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Oferta_Nao_Selecionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo cancelado..
        /// </summary>
        internal static string Mensagem_Informativa_Processo_Cancelado {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Processo_Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo encerrado..
        /// </summary>
        internal static string Mensagem_Informativa_Processo_Encerrado {
            get {
                return ResourceManager.GetString("Mensagem_Informativa_Processo_Encerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você ainda não realizou o seu agendamento..
        /// </summary>
        internal static string Mensagem_NaoIniciouAgendamento {
            get {
                return ResourceManager.GetString("Mensagem_NaoIniciouAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você ainda não realizou a entrega da sua documentação..
        /// </summary>
        internal static string Mensagem_NaoIniciouEntregaDocumentacao {
            get {
                return ResourceManager.GetString("Mensagem_NaoIniciouEntregaDocumentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você ainda não iniciou sua inscrição..
        /// </summary>
        internal static string Mensagem_NaoIniciouInscricao {
            get {
                return ResourceManager.GetString("Mensagem_NaoIniciouInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem inscrições em aberto..
        /// </summary>
        internal static string Mensagem_Nenhuma_Inscricao_Aberta {
            get {
                return ResourceManager.GetString("Mensagem_Nenhuma_Inscricao_Aberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento indisponível..
        /// </summary>
        internal static string Mensagem_Nenhuma_Inscricao_Aberta_AGENDAMENTO {
            get {
                return ResourceManager.GetString("Mensagem_Nenhuma_Inscricao_Aberta_AGENDAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega de documentação indisponível..
        /// </summary>
        internal static string Mensagem_Nenhuma_Inscricao_Aberta_ENTREGA_DE_DOCUMENTACAO {
            get {
                return ResourceManager.GetString("Mensagem_Nenhuma_Inscricao_Aberta_ENTREGA_DE_DOCUMENTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição indisponível..
        /// </summary>
        internal static string Mensagem_Nenhuma_Inscricao_Aberta_INSCRICAO {
            get {
                return ResourceManager.GetString("Mensagem_Nenhuma_Inscricao_Aberta_INSCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disponível para emissão..
        /// </summary>
        internal static string Mensagem_Tooltip_Botao_Emitir_Documentacao {
            get {
                return ResourceManager.GetString("Mensagem_Tooltip_Botao_Emitir_Documentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendário.
        /// </summary>
        internal static string Texto_Calendario {
            get {
                return ResourceManager.GetString("Texto_Calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        internal static string Texto_Fim {
            get {
                return ResourceManager.GetString("Texto_Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string Texto_Inicio {
            get {
                return ResourceManager.GetString("Texto_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mais informações.
        /// </summary>
        internal static string Texto_Mais_Informacoes {
            get {
                return ResourceManager.GetString("Texto_Mais_Informacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram encontrados resultados para a sua pesquisa..
        /// </summary>
        internal static string Texto_Nao_foram_encontrados {
            get {
                return ResourceManager.GetString("Texto_Nao_foram_encontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suas inscrições.
        /// </summary>
        internal static string Titulo_Inscricoes {
            get {
                return ResourceManager.GetString("Titulo_Inscricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seus agendamentos.
        /// </summary>
        internal static string Titulo_Inscricoes_Agendamento {
            get {
                return ResourceManager.GetString("Titulo_Inscricoes_Agendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veja o que temos para você:.
        /// </summary>
        internal static string Titulo_Inscricoes_Em_Aberto {
            get {
                return ResourceManager.GetString("Titulo_Inscricoes_Em_Aberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seus Documentos.
        /// </summary>
        internal static string Titulo_Inscricoes_Entrega_De_Documentacao {
            get {
                return ResourceManager.GetString("Titulo_Inscricoes_Entrega_De_Documentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suas Inscrições.
        /// </summary>
        internal static string Titulo_Inscricoes_Inscricao {
            get {
                return ResourceManager.GetString("Titulo_Inscricoes_Inscricao", resourceCulture);
            }
        }
    }
}
