//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.Inscricoes.Common.Areas.RES.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.Inscricoes.Common.Areas.RES.Resources.ExceptionsResource", typeof(ExceptionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato do token &quot;{0}&quot; é inválido!.
        /// </summary>
        public static string ERR_FormatoDeTokenInvalidoException {
            get {
                return ResourceManager.GetString("ERR_FormatoDeTokenInvalidoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve existir ao menos uma identidade visual ativa..
        /// </summary>
        public static string ERR_NaoExisteIdentidadeVisualAtivaException {
            get {
                return ResourceManager.GetString("ERR_NaoExisteIdentidadeVisualAtivaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir o cliente. Ele já está sendo utilizado por um ou mais códigos de autorização..
        /// </summary>
        public static string FK_codigo_autorizacao_01 {
            get {
                return ResourceManager.GetString("FK_codigo_autorizacao_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir o cliente. Ele já está sendo utilizado por um ou mais processos..
        /// </summary>
        public static string FK_processo_02 {
            get {
                return ResourceManager.GetString("FK_processo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir a unidade responsável. Ela já está sendo utilizada por um ou mais processos..
        /// </summary>
        public static string FK_processo_03 {
            get {
                return ResourceManager.GetString("FK_processo_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir a associação de unidade responsável x tipo de processo. Já existe uma identidade visual configurada para ela..
        /// </summary>
        public static string FK_unidade_responsavel_tipo_processo_identidade_visual_01 {
            get {
                return ResourceManager.GetString("FK_unidade_responsavel_tipo_processo_identidade_visual_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este sistema/origem já foi utilizado em processo(s) da unidade responsável {0}. A associação do sistema/origem não pode ser alterada..
        /// </summary>
        public static string SistemaOrigemJaAssociadoException {
            get {
                return ResourceManager.GetString("SistemaOrigemJaAssociadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um cliente cadastrado com esse nome..
        /// </summary>
        public static string UN_cliente_01 {
            get {
                return ResourceManager.GetString("UN_cliente_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma unidade responsável cadastrada com esse nome..
        /// </summary>
        public static string UN_unidade_responsavel_01 {
            get {
                return ResourceManager.GetString("UN_unidade_responsavel_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de custo já está configurado para essa unidade responsável..
        /// </summary>
        public static string UN_unidade_responsavel_centro_custo_01 {
            get {
                return ResourceManager.GetString("UN_unidade_responsavel_centro_custo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de formulário já está configurado para essa unidade responsável..
        /// </summary>
        public static string UN_unidade_responsavel_tipo_formulario_01 {
            get {
                return ResourceManager.GetString("UN_unidade_responsavel_tipo_formulario_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de processo já está configurado para essa unidade responsável..
        /// </summary>
        public static string UN_unidade_responsavel_tipo_processo_01 {
            get {
                return ResourceManager.GetString("UN_unidade_responsavel_tipo_processo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de hierarquia de oferta já está configurado para essa unidade responsável com esse tipo de processo..
        /// </summary>
        public static string UN_unidade_responsavel_tipo_processo_hierarquia_01 {
            get {
                return ResourceManager.GetString("UN_unidade_responsavel_tipo_processo_hierarquia_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma identidade visual com este nome para esta unidade responsável x tipo de processo..
        /// </summary>
        public static string UN_unidade_responsavel_tipo_processo_id_visual_01 {
            get {
                return ResourceManager.GetString("UN_unidade_responsavel_tipo_processo_id_visual_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este tipo de formulário já foi utilizado em processo(s) da unidade responsável &quot;{0}&quot;. A associação do tipo de formulário não pode ser alterada, somente desativada..
        /// </summary>
        public static string UnidadeResponsavelTipoFormularioAlterException {
            get {
                return ResourceManager.GetString("UnidadeResponsavelTipoFormularioAlterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este tipo de formulário já foi utilizado em processo(s) da unidade responsável &quot;{0}&quot;. A associação do tipo de formulário não pode ser excluída, somente desativada..
        /// </summary>
        public static string UnidadeResponsavelTipoFormularioExcludeException {
            get {
                return ResourceManager.GetString("UnidadeResponsavelTipoFormularioExcludeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de hierarquia &quot;{0}&quot; já foi utilizado em um processo da unidade responsável &quot;{1}&quot;, para o tipo de processo &quot;{2}&quot;. A associação do tipo de hierarquia não pode ser alterada, tampouco excluída, somente desativada..
        /// </summary>
        public static string UnidadeResponsavelTipoHierarquiaExcludeException {
            get {
                return ResourceManager.GetString("UnidadeResponsavelTipoHierarquiaExcludeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de processo &quot;{0}&quot; já foi utilizado em um processo da unidade responsável &quot;{1}&quot;. A associação do tipo de processo não pode ser alterada, somente desativada..
        /// </summary>
        public static string UnidadeResponsavelTipoProcessoAlterException {
            get {
                return ResourceManager.GetString("UnidadeResponsavelTipoProcessoAlterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de processo &quot;{0}&quot; já foi utilizado em um processo da unidade responsável &quot;{1}&quot;. A associação do tipo de processo não pode ser excluída, somente desativada..
        /// </summary>
        public static string UnidadeResponsavelTipoProcessoExcludeException {
            get {
                return ResourceManager.GetString("UnidadeResponsavelTipoProcessoExcludeException", resourceCulture);
            }
        }
    }
}
