//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Inscricao.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Inscricao.App_GlobalResources.MetadataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        public static string Class_ArquivoAnexado {
            get {
                return ResourceManager.GetString("Class_ArquivoAnexado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string Class_Bairro {
            get {
                return ResourceManager.GetString("Class_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string Class_Cep {
            get {
                return ResourceManager.GetString("Class_Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Class_Cidade {
            get {
                return ResourceManager.GetString("Class_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Class_CidadeNaturalidade {
            get {
                return ResourceManager.GetString("Class_CidadeNaturalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. área.
        /// </summary>
        public static string Class_CodigoArea {
            get {
                return ResourceManager.GetString("Class_CodigoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. país.
        /// </summary>
        public static string Class_CodigoPais {
            get {
                return ResourceManager.GetString("Class_CodigoPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País de origem.
        /// </summary>
        public static string Class_CodigoPaisNacionalidade {
            get {
                return ResourceManager.GetString("Class_CodigoPaisNacionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string Class_Complemento {
            get {
                return ResourceManager.GetString("Class_Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da nova senha​​.
        /// </summary>
        public static string Class_ConfirmarNovaSenha {
            get {
                return ResourceManager.GetString("Class_ConfirmarNovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceito receber informações sobre processos seletivos, bolsas de estudo, matrícula e comunicações da PUC Minas. Posso cancelar a assinatura a qualquer momento. Ao aceitar este termo declaro ser maior de 18 (dezoito) anos..
        /// </summary>
        public static string Class_ConsentimentoLGPD {
            get {
                return ResourceManager.GetString("Class_ConsentimentoLGPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondência.
        /// </summary>
        public static string Class_Correspondencia {
            get {
                return ResourceManager.GetString("Class_Correspondencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Class_Correspondencia_FALSE {
            get {
                return ResourceManager.GetString("Class_Correspondencia_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Class_Correspondencia_TRUE {
            get {
                return ResourceManager.GetString("Class_Correspondencia_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string Class_Cpf {
            get {
                return ResourceManager.GetString("Class_Cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        public static string Class_DataNascimento {
            get {
                return ResourceManager.GetString("Class_DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Class_DescPaisSelecionado {
            get {
                return ResourceManager.GetString("Class_DescPaisSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Class_Descricao {
            get {
                return ResourceManager.GetString("Class_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Class_DescricaoArquivoAnexado {
            get {
                return ResourceManager.GetString("Class_DescricaoArquivoAnexado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil.
        /// </summary>
        public static string Class_DescricaoEstadoCivil {
            get {
                return ResourceManager.GetString("Class_DescricaoEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da naturalidade.
        /// </summary>
        public static string Class_DescricaoNaturalidadeEstrangeira {
            get {
                return ResourceManager.GetString("Class_DescricaoNaturalidadeEstrangeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF (naturalidade).
        /// </summary>
        public static string Class_Estado {
            get {
                return ResourceManager.GetString("Class_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil.
        /// </summary>
        public static string Class_EstadoCivil {
            get {
                return ResourceManager.GetString("Class_EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string Class_Logradouro {
            get {
                return ResourceManager.GetString("Class_Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade.
        /// </summary>
        public static string Class_Nacionalidade {
            get {
                return ResourceManager.GetString("Class_Nacionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Class_Nome {
            get {
                return ResourceManager.GetString("Class_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Class_NomeCidade {
            get {
                return ResourceManager.GetString("Class_NomeCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da mãe.
        /// </summary>
        public static string Class_NomeMae {
            get {
                return ResourceManager.GetString("Class_NomeMae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do pai.
        /// </summary>
        public static string Class_NomePai {
            get {
                return ResourceManager.GetString("Class_NomePai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome reduzido (Apelido).
        /// </summary>
        public static string Class_NomeReduzido {
            get {
                return ResourceManager.GetString("Class_NomeReduzido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome social.
        /// </summary>
        public static string Class_NomeSocial {
            get {
                return ResourceManager.GetString("Class_NomeSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string Class_NovaSenha {
            get {
                return ResourceManager.GetString("Class_NovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Class_Numero {
            get {
                return ResourceManager.GetString("Class_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string Class_NumeroIdentidade {
            get {
                return ResourceManager.GetString("Class_NumeroIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passaporte.
        /// </summary>
        public static string Class_NumeroPassaporte {
            get {
                return ResourceManager.GetString("Class_NumeroPassaporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Órgão emissor RG.
        /// </summary>
        public static string Class_OrgaoEmissorIdentidade {
            get {
                return ResourceManager.GetString("Class_OrgaoEmissorIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País de origem.
        /// </summary>
        public static string Class_PaisNacionalidade {
            get {
                return ResourceManager.GetString("Class_PaisNacionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Class_Seq {
            get {
                return ResourceManager.GetString("Class_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade   (naturalidade).
        /// </summary>
        public static string Class_SeqCidade {
            get {
                return ResourceManager.GetString("Class_SeqCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string Class_SeqDocumentoRequerido {
            get {
                return ResourceManager.GetString("Class_SeqDocumentoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de inscrição.
        /// </summary>
        public static string Class_SeqInscricao {
            get {
                return ResourceManager.GetString("Class_SeqInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Class_SeqPais {
            get {
                return ResourceManager.GetString("Class_SeqPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Class_Sexo {
            get {
                return ResourceManager.GetString("Class_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Class_SiglaUf {
            get {
                return ResourceManager.GetString("Class_SiglaUf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string Class_TipoDocumento {
            get {
                return ResourceManager.GetString("Class_TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de endereço.
        /// </summary>
        public static string Class_TipoEndereco {
            get {
                return ResourceManager.GetString("Class_TipoEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de endereço eletrônico.
        /// </summary>
        public static string Class_TipoEnderecoEletronico {
            get {
                return ResourceManager.GetString("Class_TipoEnderecoEletronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de telefone.
        /// </summary>
        public static string Class_TipoTelefone {
            get {
                return ResourceManager.GetString("Class_TipoTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total geral.
        /// </summary>
        public static string Class_TotalGeral {
            get {
                return ResourceManager.GetString("Class_TotalGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF RG.
        /// </summary>
        public static string Class_UfIdentidade {
            get {
                return ResourceManager.GetString("Class_UfIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Class_UfNaturalidade {
            get {
                return ResourceManager.GetString("Class_UfNaturalidade", resourceCulture);
            }
        }
    }
}
