//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.TipoHierarquiaOferta.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.TipoHierarquiaOferta.App_LocalResources.Me" +
                            "tadataResource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de item de hierarquia de oferta superior.
        /// </summary>
        public static string ItemHierarquiaOfertaViewModel_DescricaoPai {
            get {
                return ResourceManager.GetString("ItemHierarquiaOfertaViewModel_DescricaoPai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pemite cadastro de oferta.
        /// </summary>
        public static string ItemHierarquiaOfertaViewModel_HabilitaCadastroOferta {
            get {
                return ResourceManager.GetString("ItemHierarquiaOfertaViewModel_HabilitaCadastroOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ItemHierarquiaOfertaViewModel_HabilitaCadastroOferta_FALSE {
            get {
                return ResourceManager.GetString("ItemHierarquiaOfertaViewModel_HabilitaCadastroOferta_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ItemHierarquiaOfertaViewModel_HabilitaCadastroOferta_TRUE {
            get {
                return ResourceManager.GetString("ItemHierarquiaOfertaViewModel_HabilitaCadastroOferta_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de item de hierarquia de oferta.
        /// </summary>
        public static string ItemHierarquiaOfertaViewModel_SeqTipoItemHierarquiaOferta {
            get {
                return ResourceManager.GetString("ItemHierarquiaOfertaViewModel_SeqTipoItemHierarquiaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID inválido..
        /// </summary>
        public static string TipoHierarquiaOfertaFiltroViewModel_Seq_MaxValue {
            get {
                return ResourceManager.GetString("TipoHierarquiaOfertaFiltroViewModel_Seq_MaxValue", resourceCulture);
            }
        }
    }
}
