#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SMC.Framework;
    using SMC.Framework.DataAnnotations;
    using SMC.Framework.Extensions;
    using SMC.Framework.Ioc;
    using SMC.Framework.Mapper;
    using SMC.Framework.Model;
    using SMC.Framework.Security;
    using SMC.Framework.Service.Security;
    using SMC.Framework.UI.Mvc;
    using SMC.Framework.UI.Mvc.Dynamic;
    using SMC.Framework.UI.Mvc.Exceptions;
    using SMC.Framework.UI.Mvc.Helpers;
    using SMC.Framework.UI.Mvc.Html;
    using SMC.Framework.UI.Mvc.Html.DataSelector;
    using SMC.Framework.UI.Mvc.Util;
    using SMC.Framework.Util;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/INS/Lookups/Oferta/Views/_LookupSelecaoOfertaInscricaoLista.cshtml")]
    public partial class _Areas_INS_Lookups_Oferta_Views__LookupSelecaoOfertaInscricaoLista_cshtml : SMC.Framework.UI.Mvc.SMCWebViewPage<dynamic>
    {
        public _Areas_INS_Lookups_Oferta_Views__LookupSelecaoOfertaInscricaoLista_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

  
    object sel = ViewBag.DataSelectorSelectedValue;
    bool allowSearch = (bool)!ViewBag.DataSelectorTreeViewAllowSearch;
    bool expandedTree = (bool)Session["TreeExpanded"];
    var result = Smc.DataSelectorTreeView(sel, false, allowSearch, expandedTree);

    if (result is SMCTreeViewFluentConfiguration<object>)
    {
        var treeview = result as SMCTreeViewFluentConfiguration<object>;
        treeview.Expanded(expandedTree);
        treeview.CssClass("smc-gpi-treeview-button ");
        treeview.ContentTemplate(

item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

WriteLiteralTo(__razor_template_writer, "\r\n");

    
      
        var node = item.Value as SMC.Inscricoes.UI.Mvc.Areas.INS.Lookups.LookupSelecaoOfertaInscricaoViewModel;
    
WriteLiteralTo(__razor_template_writer, "\r\n");

    
     if (node.IsLeaf && node.DescricaoComplementar != null)
    {
        
WriteTo(__razor_template_writer, Smc.ButtonSet().Type(SMCButtonSetType.Secondary).CssClass("smc-sga-alinhamento-botao-secundario")
                        .AddButton(Smc.Button(SMCMvcConsts.MODAL_BEHAVIOR_OPEN)
                            .Attribute(SMCMvcConsts.MODAL_ID, "modalVisualizarMaisInformacoes")
                            .Attribute(SMCMvcConsts.MODAL_TITLE, Smc.GetUIResource("MaisInformacoes"))
                            .Ajax(isPost: false)
                            .CssClass("smc-btn-visualizar-ico").Tooltip(Smc.GetUIResource("MaisInformacoes"))
                            .Text(Smc.GetUIResource("MaisInformacoes"))
                            .Action("VisualizarDetalhesOferta", "Inscricao", new { seqOferta = SMC.Framework.Security.SMCDESCrypto.EncryptNumberForURL(node.Seq) })
                            )
        );

         
    }

})
       );
}

WriteLiteral("\r\n\r\n");

Write(result);

        }
    }
}
#pragma warning restore 1591
