//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC.GPI.Administrativo.Areas.INS.Views.TipoDocumento.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC.GPI.Administrativo.Areas.INS.Views.TipoDocumento.App_LocalResources.MetadataR" +
                            "esource", typeof(MetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string TipoDocumentoFiltroViewModel_Descricao {
            get {
                return ResourceManager.GetString("TipoDocumentoFiltroViewModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite vários arquivos?.
        /// </summary>
        public static string TipoDocumentoFiltroViewModel_PermiteVariosArquivos {
            get {
                return ResourceManager.GetString("TipoDocumentoFiltroViewModel_PermiteVariosArquivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string TipoDocumentoFiltroViewModel_Seq {
            get {
                return ResourceManager.GetString("TipoDocumentoFiltroViewModel_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de emissão.
        /// </summary>
        public static string TipoDocumentoFiltroViewModel_TipoEmissao {
            get {
                return ResourceManager.GetString("TipoDocumentoFiltroViewModel_TipoEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite vários arquivos?.
        /// </summary>
        public static string TipoDocumentoListaViewModel_PermiteVariosArquivos {
            get {
                return ResourceManager.GetString("TipoDocumentoListaViewModel_PermiteVariosArquivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de emissão.
        /// </summary>
        public static string TipoDocumentoListaViewModel_TipoEmissao {
            get {
                return ResourceManager.GetString("TipoDocumentoListaViewModel_TipoEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite vários arquivos?.
        /// </summary>
        public static string TipoDocumentoViewModel_PermiteVariosArquivos {
            get {
                return ResourceManager.GetString("TipoDocumentoViewModel_PermiteVariosArquivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string TipoDocumentoViewModel_Seq {
            get {
                return ResourceManager.GetString("TipoDocumentoViewModel_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de emissão.
        /// </summary>
        public static string TipoDocumentoViewModel_TipoEmissao {
            get {
                return ResourceManager.GetString("TipoDocumentoViewModel_TipoEmissao", resourceCulture);
            }
        }
    }
}
